Repository pytorch/xla, pull requests merged in 2022-12, with the labels that each got.

#4257 Clean up some XLATensor unused interfaces
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: ltc

#4260 Move tensor methods out from XLATensor
  test/cpp/test_tensor.cpp
  torch_xla/csrc/aten_autograd_ops.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/index_ops.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/tensor_ops.cpp
Labels: ltc

#4259 Enable dynamic shape tests on TPUVM
  test/run_tests.sh
Labels: dynamism

#4271 [LTC] Naively inherits LazyTensor
  torch_xla/csrc/tensor.h
Labels: REMOVE_TORCH_PIN, ltc

#4270 Introduce XLAGraphExecutor
  test/cpp/torch_xla_test.cpp
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/index_ops.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4263 [PJRT] Create function to spawn threads instead of processes.
  test/pjrt/test_experimental_pjrt_tpu.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4282 Lower _native_batch_norm_legit
  test/test_ops.py
  torch_xla/csrc/aten_xla_type.cpp
  xla_native_functions.yaml
Labels: op lowering

#4292 Sharding annotation for empty node
  test/cpp/test_xla_sharding.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: DO_NOT_MERGE_YET, SPMD

#4293 api to grab running seed as device data
  test/dynamo/test_dynamo_integrations_util.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: dynamo

#4296 [LTC] Inherits LazyGraphExecutor
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: REMOVE_TORCH_PIN, ltc

#4294 [LTC] Reuse some methods from LazyTensor
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_graph_executor.cpp
Labels: ltc

#4302 Add a simple gpu doc
  docs/gpu.md
Labels: xla:gpu

#4303 [LTC] Reuse more upstream LazyGraphExecutor data structures
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: REMOVE_TORCH_PIN, ltc

#4309 Revert "[LTC] Reuse more upstream LazyGraphExecutor data structures (…
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4312 [LTC] Reuse more upstream LazyGraphExecutor data structures
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4299 [WIP]Disable all failed PyTorch test
  test/pytorch_test_base.py
Labels: Test

#4291 Add one more symint expand test.
  test/test_dynamic_shapes.py
Labels: dynamism, Test

#4307 [LTC] Inherits LazyGraphExecutor::DeviceContextArena
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4285 Correctly configure PJRT execution when nprocs=1.
  test/pjrt/test_experimental_pjrt.py
  test/pjrt/test_experimental_pjrt_tpu.py
  torch_xla/core/xla_model.py
  torch_xla/distributed/xla_multiprocessing.py
  torch_xla/experimental/pjrt.py
  torch_xla/experimental/tpu.py
Labels: runtime

#4314 [LTC] Adopt more LazyGraphExecutor virtual interfaces
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4315 [LTC] Override LazyGraphExecutor::RunPostOrder()
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc

#4317 [LTC] Adopt even more LazyTensor interfaces
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: ltc

#4337 Install sympy to ci base docker image
  .circleci/docker/install_conda.sh
Labels: dependencies

#4336 [SPMD] Use d2d replication via CopyToDevice
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/xla_sharding_util.cpp
Labels: runtime, SPMD

#4331 Add test to verify that virtual device reduces outbound data size for…
  test/test_xla_sharding.py
Labels: SPMD

#4334 [PJRT] Fix TPU local ordinal calculation
  test/pjrt/test_experimental_pjrt_tpu.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4372 Enable FSDP test on gpu ci
  .circleci/common.sh
  test/test_train_mp_imagenet_fsdp.py
Labels: fsdp

#4367 Update README link to section
  README.md
Labels: documentation

#4318 add `auto_wrap_policy` into XLA FSDP for automatic wrapping
  docs/fsdp.md
  test/test_train_mp_imagenet_fsdp.py
  test/test_train_mp_mnist_fsdp_with_ckpt.py
  torch_xla/distributed/fsdp/wrap.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
Labels: fsdp

#4378 Add gpu fsdp auto_wrap test
  .circleci/common.sh
Labels: fsdp

#4311 Improve numerical stability of torch.sigmoid
  test/test_operations.py
  torch_xla/csrc/elementwise.cpp
Labels: op lowering, xla:gpu

#4389 Add GPU doc to readme
  README.md
  docs/gpu.md
Labels: documentation

#4380 Update `libtpu` version to Dec17
  setup.py
Labels: tf-update

#4397 [LTC] Final tweaks on XLATensor and XLAGraphExecutor
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: ltc
