Repository pytorch/xla, pull requests merged in 2022-06, with the labels that each got.

#3628 Refactor PjRt tests to take advantage of dynamic libtpu loading
  test/pjrt/args_parse.py
  test/pjrt/common.py
  test/pjrt/run_all_chips.sh
  test/pjrt/test_train_pjrt_imagenet.py
  test/pjrt/test_train_pjrt_mnist.py
Labels: runtime

#3627 Implement the remaining backend interface
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/computation.cpp
  torch_xla/csrc/computation.h
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc

#3624 Remove l1 loss backward
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/l1_loss.cpp
  torch_xla/csrc/ops/l1_loss.h
  torch_xla/csrc/ops/l1_loss_backward.cpp
  torch_xla/csrc/ops/l1_loss_backward.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/reduction.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: high risk

#3554 Support sum with dim==None
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#3652 Revert "Revert "[TEST] test XLA CI w/ SymInts""
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/tensor_impl.h
Labels: dynamism

#3656 Implement IRBuilder
  torch_xla/csrc/ir_builder.h
Labels: ltc

#3649 Register XLA lazy backend
  .gitignore
  scripts/generate_code.sh
  setup.py
  test/cpp/torch_xla_test.cpp
  torch_xla/__init__.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc
