Repository pytorch/xla, pull requests merged in 2022-09, with the labels that each got.

#3944 Clean up SymIntElements
  test/cpp/CMakeLists.txt
  test/cpp/test_symint.cpp
  torch_xla/csrc/torch_util.cpp
  torch_xla/csrc/torch_util.h
Labels: dynamism

#3952 Fix DDP initialization with XLA backend
  test/pjrt/test_ddp.py
  test/run_tests.sh
  test/test_torch_distributed_xla_backend.py
  torch_xla/core/xla_model.py
  torch_xla/distributed/xla_backend.py
  torch_xla/experimental/pjrt.py
Labels: runtime, ddp

#3962 [SPMD][PoC] Tensor sharding util
  test/cpp/CMakeLists.txt
  test/cpp/test_xla_sharding.cpp
  test/run_tests.sh
  test/test_xla_sharding.py
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/experimental/xla_sharded_tensor.py
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#3987 Companion PR for https://github.com/pytorch/pytorch/pull/84837
  test/cpp/test_symint.cpp
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN, REBASE_BEFORE_MERGE

#3954 Make SizeNode to use XlaShape and add test
  test/cpp/test_ir.cpp
  test/cpp/test_symint.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#3958 Add upper_bound_ and is_symbolic_ to SizeNode
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#3963 [SPMD][PoC] InputHandler for input sharding
  test/cpp/test_xla_sharding.cpp
  test/run_tests.sh
  third_party/xla_client/BUILD
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  third_party/xla_client/xrt_computation_client.cc
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/tensor_util.h
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: SPMD

#4004 Expand static symint test
  test/cpp/test_aten_xla_tensor.cpp
Labels: dynamism

#4001 switch everything to XLASymIntNodeImpl
  test/cpp/test_symint.cpp
  torch_xla/csrc/torch_util.cpp
Labels: dynamism

#3992 allow FSDP wrapping and sharding over modules on CPU devices
  test/test_train_mp_imagenet_fsdp.py
  test/test_train_mp_mnist_fsdp_with_ckpt.py
  torch_xla/distributed/fsdp/README.md
  torch_xla/distributed/fsdp/xla_flatten_params_wrapper.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
Labels: fsdp

#4006 DimCast Helpers
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#3999 Codegen hardshrink
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/hardshrink.cpp
  torch_xla/csrc/ops/hardshrink.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3843 Op lowering for Einsum
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_autograd_ops.cpp
  torch_xla/csrc/aten_autograd_ops.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
  torch_xla/csrc/ops/einsum.cpp
  torch_xla/csrc/ops/einsum.h
  torch_xla/csrc/ops/einsum_backward.cpp
  torch_xla/csrc/ops/einsum_backward.h
  torch_xla/csrc/ops/einsum_utilities.h
  torch_xla/csrc/ops/infer_output_shape.cpp
  torch_xla/csrc/ops/infer_output_shape.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/reduction.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: op lowering, REMOVE_TORCH_PIN

#3990 Add upsample_nearest/bilinear implementation for CPU and GPU
  test/cpp/test_aten_xla_tensor.cpp
  test/pytorch_test_base.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/resize_ops.cpp
Labels: op lowering

#3913 Ceil forr round trunc int
  torch_xla/csrc/ops/ops_lower_fn.cpp
Labels: REMOVE_TORCH_PIN

#4008 Cache dynamic ir result
  test/cpp/test_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#4002 Codegen HardshrinkBackward and SoftshrinkBackward
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/ops/shrink_backward.cpp
  torch_xla/csrc/ops/shrink_backward.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3542 [xla][cpu] Add Arm Compute Library (ACL) build option for torch-xla
  build_torch_xla_libs.sh
Labels: arm

#3889 Support `expand.symint` with real symbolic symint
  test/cpp/cpp_test_util.cpp
  test/cpp/cpp_test_util.h
  test/cpp/test_aten_xla_tensor.cpp
  test/cpp/test_ir.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/data_ops.cpp
  torch_xla/csrc/data_ops.h
  torch_xla/csrc/ops/expand_symint.cpp
  torch_xla/csrc/ops/expand_symint.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
Labels: dynamism

#4014 [DDP] Add a test case for XRT
  test/__init__.py
  test/distributed_util.py
  test/pjrt/__init__.py
  test/pjrt/test_ddp.py
  test/run_tests.sh
  test/test_ddp.py
Labels: ddp

#4026 Add "getDynamicValue" for SizeAdd node.
  test/cpp/test_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#4042 Add getDynamicValue for SizeMul and SizeDiv nodes.
  test/cpp/test_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#4045 Minor clean up for expand_symint
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
Labels: dynamism

#4050 [DDP] Disable test/test_ddp.py in a GPU env
  test/test_ddp.py
Labels: ddp

#4035 Update amax/amin/norm signatures with int[*]? dim
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
Labels: REMOVE_TORCH_PIN, REBASE_BEFORE_MERGE

#4051 Fix a divide-by-0 error for SizeDiv node.
  test/cpp/test_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
Labels: dynamism

#3909 Add `sym_sizes` with dynamic shape support
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/tensor_impl.h
Labels: dynamism

#3660 add aarch64 build scripts for torch and xla wheel building
  scripts/build_torch_wheels.sh
Labels: arm

#4060 Fix `ExpectCounterNotChanged` to correctly account for `_symint`
  test/cpp/torch_xla_test.cpp
Labels: dynamism

#4057 Add 'Add' and 'FloorDiv' to XLASymIntNodeImpl
  test/cpp/test_symint.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#3994 Adding SizeConstant
  test/cpp/test_symint.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#3983 [Distributed] Companion fix after pytorch PR73164
  test/test_torch_distributed_xla_backend.py
Labels: REMOVE_TORCH_PIN, REBASE_BEFORE_MERGE
