Repository pytorch/xla, pull requests merged in 2022-07, with the labels that each got.

#3672 Make computation to take string when used for compilation
  third_party/xla_client/computation_client.h
  torch_xla/csrc/computation.cpp
  torch_xla/csrc/computation.h
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc

#3690 Revert "Revert "Support sum with dim==None""
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#3683 Remove kl_div_backward
  test/cpp/test_aten_xla_tensor.cpp
  torch_patches/.torch_pin
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_ops.cpp
  torch_xla/csrc/tensor_ops.h
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, high risk

#3696 Implement ir builder
  torch_xla/csrc/ir_builder.h
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc

#3695 Default device backendintf
  test/cpp/torch_xla_test.cpp
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc

#3722 Codegen Rsqrt
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3697 Add XLABackendIntf test
  test/cpp/CMakeLists.txt
  test/cpp/test_xla_backend_intf.cpp
  torch_xla/csrc/xla_backend_impl.cpp
  torch_xla/csrc/xla_backend_impl.h
Labels: ltc

#3728 Codegen tril, tril_, triu, triu_
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/ops/tril.cpp
  torch_xla/csrc/ops/tril.h
  torch_xla/csrc/ops/triu.cpp
  torch_xla/csrc/ops/triu.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3735 Add `dynamic_ir`
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
Labels: dynamism

#3734 Codegen hardsigmoid hardswish
  torch_patches/.torch_pin
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3747 Revert "Revert "Codegen hardsigmoid hardswish""
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3743 Codegen log_sigmoid_forward/backward
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3727 Add shape fn to adaptive_average_pool2d/backward +log_softmax
  test/cpp/test_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/adaptive_avg_pool2d.cpp
  torch_xla/csrc/ops/adaptive_avg_pool2d.h
  torch_xla/csrc/ops/generic.cpp
  torch_xla/csrc/ops/generic.h
  torch_xla/csrc/ops/log_softmax.cpp
  torch_xla/csrc/ops/log_softmax.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
Labels: ltc

#3752 Support torch.mean with dim=None
  torch_patches/.torch_pin
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#3744 Add `SymIntElements` to enable unpacking `SymIntArrayRef`
  torch_xla/csrc/torch_util.cpp
  torch_xla/csrc/torch_util.h
Labels: dynamism

#3762 Partially codegen adaptive
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/ops/adaptive_avg_pool2d.cpp
  torch_xla/csrc/ops/adaptive_avg_pool2d.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3791 Use two existing mirrors for download_llvm_raw
  .circleci/download_llvm_raw.sh
Labels: enhancement

#3793 Rename `SymbolicIntNode` to `SymIntNodeImpl`
  torch_xla/csrc/torch_util.cpp
Labels: dynamism

#3782 Revert "Revert "Support torch.mean with dim=None (#3752)" (#3757)"
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#3780 Codegen silu selu
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3758 Full codegen for isnan
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#3802 Repair `SymIntNodeImpl` to unblock `master` HEAD
  torch_xla/csrc/torch_util.cpp
Labels: dynamism
