Repository pytorch/xla, pull requests merged in 2022-04, with the labels that each got.

#3450 Fix aten::gather
  torch_xla/csrc/ops/gather.cpp
  torch_xla/csrc/tensor_methods.cpp
Labels: bug, enhancement, op lowering

#3498 Add performance profiling tool to enable programmatic/interactive/automatic PT-XLA profile capturing
  README.md
  scripts/capture_profile.py
Labels: enhancement

#3496 Lower hardswish
  test/cpp/test_aten_xla_tensor.cpp
  test/pytorch_test_base.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: op lowering

#3505 lowering roll op
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/roll.cpp
  torch_xla/csrc/ops/roll.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  xla_native_functions.yaml
Labels: op lowering

#3457 Move device lock before the execution instead of tensor gathering
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: enhancement, perf
