Repository pytorch/xla, pull requests merged in 2022-11, with the labels that each got.

#4144 [SPMD] Test sharding_spec with clear_sharding, deepcopy
  test/run_tests.sh
  test/test_xla_sharding.py
  third_party/xla_client/computation_client.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir.h
  torch_xla/csrc/tensor.cpp
  torch_xla/experimental/xla_sharded_tensor.py
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4111 Update codegen to use xla::Shape
  scripts/gen_lazy_tensor.py
  test/cpp/test_symint.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, ltc

#4156 Enable `padded` option for even tensor sharding
  test/cpp/test_xla_sharding.cpp
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/experimental/xla_sharded_tensor.py
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4154 [LTC] Remove XLAIrBuilder::MakeView
  torch_xla/csrc/ir_builder.h
Labels: ltc

#4162 [SPMD] Mesh to support custom device order.
  test/test_xla_sharding.py
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4172 [LTC] Use upstream DeviceDataInfo
  third_party/xla_client/computation_client.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_backend_impl.h
Labels: ltc

#4176 [LTC] Employ more Computation
  torch_xla/csrc/computation.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: ltc

#4182 [LTC] Make some torch::lazy::Node* to const T
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc

#4185 Fix check_tensor_need_materialization
  test/dynamo/test_dynamo_integrations_util.py
  torch_xla/csrc/init_python_bindings.cpp
Labels: dynamo

#4178 [LTC] Use torch::lazy::Util::ComputePostOrder
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir_dump_util.cpp
  torch_xla/csrc/ir_util.cpp
  torch_xla/csrc/ir_util.h
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/tensor.cpp
Labels: ltc

#4186 [LTC] Use getBackend()->ExecuteComputation()
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
Labels: ltc

#4187 Fix multi-gpu metrics report
  third_party/xla_client/xrt_computation_client.cc
Labels: xla:gpu

#4191 [LTC] Adopt getBackend()->GetComputationDataFromNode()
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/tensor.cpp
Labels: ltc

#4195 Run cached graph api should grab device lock first
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamo

#4192 [SPMD] implement unit test cases for 5D tile sharding
  test/cpp/test_xla_sharding.cpp
  torch_xla/csrc/xla_sharding_util.cpp
Labels: SPMD

#4181 Implement `xm.rendezvous` with XLA collective communication
  test/pjrt/test_mesh_service.py
  test/run_tests.sh
  torch_xla/experimental/pjrt.py
Labels: runtime

#4196 Add a api to reset and extract RNG Seed
  test/dynamo/test_dynamo_integrations_util.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamo

#4208 Replace XLA_COUNTER with TORCH_LAZY_COUNTER
  test/cpp/metrics_snapshot.cpp
  test/test_metrics.py
  third_party/xla_client/metrics.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/tensor.cpp
Labels: REMOVE_TORCH_PIN, ltc

#4205 model should be on xla device for Dynamo torchxla_trace_once backend
  test/dynamo/test_dynamo.py
  test/dynamo/test_dynamo_integrations_util.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: REMOVE_TORCH_PIN, dynamo

#4240 Companion PR for pytorch/pytorch#89326
  torch_xla/csrc/aten_xla_type.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4237 [SPMD] do add instead of matmul in SPMD unit testing
  test/test_xla_sharding.py
Labels: SPMD

#4233 [SPMD] fixes bugs with AssignIrValue & ExecuteReplicated
  test/test_xla_sharding.py
  third_party/xla_client/pjrt_computation_client.cc
  torch_xla/csrc/tensor.cpp
Labels: SPMD

#4242 Companion PR for pytorch/pytorch#89327
  torch_xla/csrc/aten_xla_type.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4217 [LTC] Replace XLA_FN_COUNTER with TORCH_LAZY_FN_COUNTER
  CODEGEN_MIGRATION_GUIDE.md
  scripts/gen_lazy_tensor.py
  test/test_metrics.py
  third_party/xla_client/metrics.h
  torch_xla/csrc/aten_cpu_fallback.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/tensor.cpp
Labels: REMOVE_TORCH_PIN, ltc

#4245 [LTC] Replace XLA_VALUE_METRIC with TORCH_LAZY_VALUE_METRIC
  test/test_metrics.py
  third_party/xla_client/metrics.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/tensor.cpp
Labels: REMOVE_TORCH_PIN, ltc

#4247 CI requires cmake>=3.18 to install PyTorch
  .circleci/docker/install_conda.sh
Labels: high priority, dependencies

#4250 [LTC] Replace XLA_TIMED with TORCH_LAZY_TIMED
  test/test_metrics.py
  third_party/xla_client/metrics.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor_util.cpp
Labels: ltc

#4193 Experimental TPU implementation of DistributedDataParallel
  test/distributed_util.py
  test/pjrt/test_ddp.py
  test/test_ddp.py
  test/test_train_mp_imagenet.py
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/experimental/pjrt.py
  torch_xla/experimental/tpu.py
Labels: runtime, ddp

#4243 Fix `non_zero` cast issue
  test/cpp/test_aten_xla_tensor.cpp
  test/test_operations.py
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/tensor_methods.cpp
Labels: dynamism
