Repository pytorch/xla, pull requests merged in 2022-10, with the labels that each got.

#4077 [PJRT] Enable PJRT C API option
  tf_patches/patch.diff
  third_party/xla_client/BUILD
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  torch_xla/__init__.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4085 [DDP] Add a test case to test a larger model
  test/args_parse.py
  test/distributed_util.py
  test/pjrt/test_ddp.py
  test/test_ddp.py
  torch_xla/distributed/xla_multiprocessing.py
Labels: triaged

#4080 Adding bool operator and a test
  test/test_dynamic_shapes.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#4079 Add an equality node
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#4038 Use PjRt GPU client
  test/pjrt/test_experimental_pjrt_gpu.py
  test/run_tests.sh
  third_party/xla_client/BUILD
  third_party/xla_client/env_vars.cc
  third_party/xla_client/env_vars.h
  third_party/xla_client/pjrt_computation_client.cc
  torch_xla/core/xla_env_vars.py
Labels: runtime

#4076 implement XLASymIntNodeImpl::wrap
  test/test_dynamic_shapes.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#4092 Make sure `PjRtData` is not empty in `GetOpaqueHandle`
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#3684 [SPMD][PoC] compile & execute with PjRt
  test/cpp/test_xla_sharding.cpp
  test/test_xla_sharding.py
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir_dump_util.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4081 Add ConvertXlaShapeToLazy helper function
  test/cpp/CMakeLists.txt
  test/cpp/test_lazy.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
Labels: ltc

#4105 Set default xla_gpu_force_compilation_parallelism
  torch_xla/__init__.py
Labels: xla:gpu

#4107 [PERF] Add a util script to analyse perf results
  test/utils/train_mp_result_analyzer.py
Labels: triaged

#4112 [PERF] Adds epoch to mnist test logs
  test/test_train_mp_mnist.py
Labels: triaged

#4106 [LTC] Adopt the extensible LazyGraphExecutor
  torch_xla/csrc/xla_backend_impl.cpp
Labels: triaged, ltc

#4118 Test fix for Bernoulli
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4119 Dynamo Poc
  test/run_tests.sh
  test/test_dynamo_integrations_util.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamo

#4129 [LTC] Remove IrBuilder trimmed interfaces
  torch_xla/csrc/ir_builder.h
Labels: ltc
