Repository pytorch/xla, pull requests merged in 2022-05, with the labels that each got.

#3463 Start implementation of PjRtComputationClient.
  test/run_tests.sh
  third_party/xla_client/BUILD
  third_party/xla_client/computation_client.cc
  third_party/xla_client/env_vars.cc
  third_party/xla_client/env_vars.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#3561 Shift int only
  test/cpp/test_aten_xla_tensor.cpp
Labels: REMOVE_TORCH_PIN

#3544 Codegen Abs and Maximum op
  scripts/gen_lazy_tensor.py
  setup.py
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/generated_file_include.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir.cpp
  torch_xla/csrc/ir.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#3550 Experimental support for single-host TPU in PjRt
  third_party/xla_client/BUILD
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#3574 Full codegen for `cos` and `cosh`
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3577 Full codegen for `sgn`, `sign`
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3580 Use upstream torch::lazy::Computation
  torch_xla/csrc/computation.h
Labels: ltc

#3578 Address review comments from #3550
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#3592 Update `googletest` dependency to its stable version `1.11.0` pin
  test/cpp/CMakeLists.txt
Labels: gtest-update

#3562 [WIP] Use XlaBackendData in PyTorch/XLA
  test/cpp/cpp_test_util.cpp
  test/cpp/test_op_by_op_executor.cpp
  test/cpp/test_replication.cpp
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/lowering_context.h
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/op_by_op_executor.h
  torch_xla/csrc/ops/device_data.cpp
  torch_xla/csrc/ops/device_data.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/tensor_util.h
  torch_xla/csrc/xla_backend_impl.h
Labels: ltc

#3576 Full codegen for `logdet`
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3607 Add PjRt tests for MNIST and ImageNet.
  test/pjrt/run_all_chips.sh
  test/pjrt/test_train_pjrt_imagenet.py
  test/pjrt/test_train_pjrt_mnist.py
Labels: runtime

#3585 Inherit from torch::lazy::LoweringContext
  test/cpp/cpp_test_util.cpp
  torch_xla/csrc/ir_dump_util.cpp
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/lowering_context.h
  torch_xla/csrc/op_by_op_executor.cpp
  torch_xla/csrc/tensor.cpp
Labels: ltc

#3571 Partially implement LTC Backend interface for PyTorch/XLA.
  torch_xla/csrc/computation.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/tensor_util.h
  torch_xla/csrc/xla_backend_impl.cpp
  torch_xla/csrc/xla_backend_impl.h
Labels: ltc

#3476 XLA SPMD PoC implementation with XRT
  setup.py
  test/cpp/test_xla_sharding.cpp
  test/test_xla_sharding.py
  third_party/xla_client/BUILD
  third_party/xla_client/xrt_computation_client.cc
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir.h
  torch_xla/csrc/ir_dump_util.cpp
  torch_xla/csrc/ir_dump_util.h
  torch_xla/csrc/lowering_context.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/experimental/__init__.py
  torch_xla/experimental/xla_sharded_tensor.py
  torch_xla/experimental/xla_sharding.py
Labels: DO_NOT_MERGE, SPMD

#3414 update tensor indexing to fail on `non_xla_tensor[xla_tensor]`
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#3614 Wrap ComputationClient::Computation inside of torch_xla::Computation
  third_party/xla_client/computation_client.h
  torch_xla/csrc/computation.cpp
  torch_xla/csrc/computation.h
  torch_xla/csrc/xla_backend_impl.cpp
Labels: ltc
