Repository pytorch/xla, pull requests merged in 2022-08, with the labels that each got.

#3805 Codegen trunc
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3796 Codegen relu and relu_
  test/cpp/test_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3809 Codegen binary_cross_entropy/backward
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/binary_cross_entropy.cpp
  torch_xla/csrc/ops/binary_cross_entropy.h
  torch_xla/csrc/ops/binary_cross_entropy_backward.cpp
  torch_xla/csrc/ops/binary_cross_entropy_backward.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/reduction.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3784 implementing sym_numel_custom
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/tensor_impl.h
Labels: REMOVE_TORCH_PIN, dynamism

#3826 Revert of #3822 "Revert "implementing sym_numel_custom""
  torch_patches/.torch_pin
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/tensor_impl.h
Labels: REMOVE_TORCH_PIN, dynamism

#3790 partially codegen adaptive_avgpool3d and backward
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/adaptive_avg_pool3d.cpp
  torch_xla/csrc/ops/adaptive_avg_pool3d.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3833 Refactor PjRt device transfers to use `BufferFromHostBuffer`
  third_party/xla_client/env_vars.cc
  third_party/xla_client/env_vars.h
  third_party/xla_client/pjrt_computation_client.cc
Labels: runtime

#3855 Remove Ger lowering as it is not needed
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  xla_native_functions.yaml
Labels: codegen

#3864 Codegen ge, gt
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  xla_native_functions.yaml
Labels: codegen

#3867 Codegen clamp_min.Tensor and clamp_max.Tensor
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  xla_native_functions.yaml
Labels: codegen

#3771 Codegen amin amax
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/amax.cpp
  torch_xla/csrc/ops/amax.h
  torch_xla/csrc/ops/amin.cpp
  torch_xla/csrc/ops/amin.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3866 Add profiler traces to `PjRtComputationClient`
  test/pjrt/test_profiler.py
  third_party/xla_client/pjrt_computation_client.cc
Labels: runtime

#3768 Codegen addcdiv and addcmul
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  xla_native_functions.yaml
Labels: codegen

#3876 Codegen lt le
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  xla_native_functions.yaml
Labels: codegen

#3890 Enable `SetUpperBound` to update DS upper bounds
  torch_xla/csrc/torch_util.h
Labels: dynamism

#3893 Codegen elu and elu_
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3865 Codegen all.dim
  scripts/gen_lazy_tensor.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/all_dim.cpp
  torch_xla/csrc/ops/all_dim.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3899 Upgrade `libtpu` version to June to
  setup.py
Labels: libtpu-update

#3888 Update `isDynamic` api to align with `is_symbolic` API in upstream
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
  torch_xla/csrc/torch_util.cpp
Labels: dynamism

#3879 codegen eq
  test/cpp/test_aten_xla_tensor.cpp
  test/pytorch_test_base.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  xla_native_functions.yaml
Labels: codegen

#3882 Codegen ne
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  xla_native_functions.yaml
Labels: codegen

#3818 Codegen take
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3907 Codegen cholesky
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/cholesky.cpp
  torch_xla/csrc/ops/cholesky.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN, codegen

#3912 Fix upstream break 83586
  test/test_ops.py
Labels: REMOVE_TORCH_PIN

#3815 Codegen for bitwise and, or, xor, and not
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/bitwise_ir_ops.cpp
  torch_xla/csrc/ops/bitwise_ir_ops.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3902 Set PJRT device assignment in order of device ID
  test/pjrt/test_experimental_pjrt_tpu.py
  test/pjrt/test_parameter_broadcast_tpu.py
  third_party/xla_client/pjrt_computation_client.cc
  torch_xla/experimental/pjrt.py
Labels: runtime

#3930 Codegen frac op
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3910 Codegen any and any.dim
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/any.cpp
  torch_xla/csrc/ops/any.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: codegen

#3929 [PjRt] Implement `xm.rendezvous` for TPU v4.
  test/pjrt/test_mesh_service.py
  torch_xla/core/xla_model.py
  torch_xla/experimental/pjrt.py
  torch_xla/experimental/tpu.py
Labels: runtime

#3948 revert numel companion PR to 84207
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/tensor_impl.h
Labels: REMOVE_TORCH_PIN

#3785 Add regression test for torch.expand
  .circleci/common.sh
  .circleci/docker/install_conda.sh
  test/run_tests.sh
  test/test_operations_hlo.py
Labels: dynamism
