Repository pytorch/xla, pull requests merged in 2023-04, with the labels that each got.

#4763 Fix XLASymNodeImpl::has_hint
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#4860 [PJRT] Add example Kaggle notebooks for PyTorch/XLA 2.0 on TPU VM
  contrib/kaggle/distributed-pytorch-xla-basics-with-pjrt.ipynb
  contrib/kaggle/pytorch-xla-2-0-on-kaggle.ipynb
Labels: runtime, documentation

#4858 Verify if abs support dynamism.
  test/test_dynamic_shapes.py
Labels: dynamism

#4882 Update for SymInt API changes
  test/cpp/test_aten_xla_tensor.cpp
  test/cpp/test_symint.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/torch_util.cpp
Labels: REMOVE_TORCH_PIN

#4894 Update PJRT readme to point to r2.0 during clone
  docs/pjrt.md
Labels: documentation

#4759 Update dynamo readme
  docs/dynamo.md
Labels: documentation

#4781 Lower linalg_vector_norm
  test/cpp/test_aten_xla_tensor.cpp
  test/test_ops.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  xla_native_functions.yaml
Labels: op lowering

#4840 Update tf pin to 03/2023
  .circleci/common.sh
  WORKSPACE
  setup.py
  test/test_fsdp_auto_wrap.py
  test/test_torch_distributed_fsdp_meta.py
  tf_patches/cudnn_int8x32.diff
  tf_patches/grpc_version.diff
  tf_patches/local_rendezvous.diff
  tf_patches/topk_rewriter.diff
  tf_patches/triton_filesystem.diff
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: tf-update

#4903 Add a test to verify nonzero correctness.
  test/ds/test_dynamic_shapes.py
Labels: dynamism

#4919 Apply sharding to all compatible input tensors
  torch_xla/core/xla_model.py
  torch_xla/distributed/parallel_loader.py
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4925 Update op lowering guide
  OP_LOWERING_GUIDE.md
Labels: documentation
