Repository pytorch/xla, pull requests merged in 2023-02, with the labels that each got.

#4542 Fix race condition on GPU
  test/test_ddp.py
  tf_patches/gpu_race_condition.diff
Labels: xla:gpu

#4530 Align the dynamo dump file with the lazy
  test/dynamo/test_dynamo_graph_dump.py
  torch_xla/csrc/xla_graph_executor.cpp
Labels: dynamo

#4508 Transfer shards from server using replication
  test/spmd/test_xla_sharding.py
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
Labels: SPMD

#4550 Make empty_symint support dynamism.
  test/cpp/test_aten_xla_tensor.cpp
  test/test_dynamic_shapes.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: dynamism

#4517 Add initial support for `scatter_reduce`
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/scatter_reduce.cpp
  torch_xla/csrc/ops/scatter_reduce.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  xla_native_functions.yaml
Labels: op lowering

#4561 Remove unused docker tagging in .circleci/config.yml
  .circleci/config.yml
Labels: bug

#4570 Actual build and install sccache from source
  .circleci/docker/Dockerfile
Labels: DO_NOT_MERGE_YET

#4583 [PJRT] Slice literals to return correct dynamic shape
  .circleci/common.sh
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#4578 Rename random_.from to random_.from_int
  torch_xla/csrc/aten_xla_type.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4591 Update the list of supported CUDA images.
  README.md
Labels: DO_NOT_MERGE_YET, cleanup

#4599 [PJRT] Use PJRT by default if XRT is not configured
  torch_xla/__init__.py
Labels: runtime

#4595 Fix fp64 div issue
  test/test_operations_hlo.py
Labels: REMOVE_TORCH_PIN

#4603 Add the counter check for dynamo tests
  test/dynamo/test_dynamo.py
  torch_xla/core/dynamo_bridge.py
Labels: dynamo

#4600 [PJRT] Use TFRT TPU client by default
  test/pjrt/test_experimental_pjrt.py
  third_party/xla_client/pjrt_computation_client.cc
  torch_xla/experimental/pjrt.py
Labels: runtime

#4606 Support dynamism on "transpose" operation.
  test/test_dynamic_shape_models.py
  test/test_dynamic_shapes.py
  torch_xla/csrc/ops/permute.cpp
  torch_xla/csrc/tensor_methods.cpp
Labels: dynamism

#4608 Add dynamic shape test for unsqueeze_copy
  test/test_dynamic_shapes.py
  torch_xla/csrc/tensor_methods.cpp
Labels: dynamism

#4573 Support multihost SPMD execution
  test/cpp/test_xla_sharding.cpp
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4612 Skip execution for extract_compiled_graph
  test/dynamo/test_dynamo.py
  test/dynamo/test_dynamo_integrations_util.py
  test/dynamo/test_num_output.py
  torch_xla/core/dynamo_bridge.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: dynamo

#4630 [PJRT] Defer default device selection until we need to know the runtime
  configuration.yaml
  test/pjrt/test_experimental_pjrt.py
  torch_xla/__init__.py
  torch_xla/core/xla_env_vars.py
  torch_xla/distributed/xla_dist.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4316 Add experimental test coverage feature
  .circleci/common.sh
  .circleci/config.yml
  .circleci/test.sh
  test/utils/run_test_coverage.sh
Labels: enhancement

#4642 Full codegen for repeat
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/ops/repeat.cpp
  torch_xla/csrc/ops/repeat.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  xla_native_functions.yaml
Labels: codegen

#4672 Fix torch-xla MSELoss to handle mixed datatype, also reuse the IR datatype instead of converting to input's.
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/tensor_methods.cpp
Labels: op lowering

#4678 Implement XLASymNodeImpl.has_hint and re-enable failing DS tests.
  test/test_dynamic_shape_models.py
  test/test_dynamic_shapes.py
  test/test_operations.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
Labels: dynamism

#4684 [PJRT] Use the new local rank env var to calculate local_ordinal
  test/pjrt/test_experimental_pjrt_tpu.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4697 Fix dynamo test no op
  test/dynamo/test_dynamo.py
Labels: dynamo

#4698 Add test for dynamo and sgd optimizer
  test/dynamo/test_dynamo.py
Labels: dynamo
