Repository pytorch/xla, pull requests merged in 2023-12, with the labels that each got.

#5950 Add all-gather coalescing for FSDP/ZeRO1
  test/test_torch_distributed_xla_backend.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/cross_replica_reduces.cpp
  torch_xla/csrc/cross_replica_reduces.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/all_gather.cpp
  torch_xla/csrc/ops/all_gather.h
  torch_xla/csrc/ops/all_reduce.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
  torch_xla/distributed/xla_backend.py
Labels: backport_2.2

#5964 [Export] Add an option to not save the weights
  test/stablehlo/test_stablehlo_save_load.py
  torch_xla/stablehlo.py
Labels: backport_2.2

#5971 Add graph hash to save tensor output
  test/dynamo/test_dynamo_graph_dump.py
  test/spmd/test_spmd_graph_dump.py
  torch_xla/csrc/debug_util.cpp
  torch_xla/csrc/debug_util.h
  torch_xla/csrc/xla_graph_executor.cpp
Labels: usability, backport_2.2

#5969 Add profiler API for async capture
  test/test_profile_mp_mnist.py
  test/test_profiler.py
  torch_xla/debug/profiler.py
Labels: backport_2.2

#5957 Fix test_dynamo_input_sharding_threashold
  test/spmd/test_dynamo_spmd.py
Labels: SPMD, backport_2.2

#5742 [SPMD] Add debug of SPMD for single/multi host
  test/run_tests.sh
  test/spmd/test_spmd_debugging.py
  test/tpu/xla_test_job.yaml
  torch_xla/distributed/spmd/__init__.py
  torch_xla/distributed/spmd/debugging.py
Labels: SPMD, backport_2.2

#6012 Update OpenXLA-pin to Nov24
  WORKSPACE
  openxla_patches/cache_urls.diff
  openxla_patches/constexpr_return.diff
  openxla_patches/gpu_race_condition.diff
  openxla_patches/gpu_topk_rewriter.diff
  setup.py
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
Labels: backport_2.2

#6021 Disable flaky test
  torch_xla/csrc/runtime/BUILD
Labels: backport_2.2

#5974 Enable Cumsum with long input
  test/cpp/test_aten_xla_tensor_2.cpp
  torch_xla/csrc/aten_xla_type.cpp
Labels: backport_2.2

#6031 Fix tensor to xla dtype conversion error
  torch_xla/csrc/dtype.cpp
Labels: bug, backport_2.2

#5800 Add a persistent cache
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/cache.h
  torch_xla/csrc/runtime/cache_test.cc
Labels: backport_2.2

#5931 Add a mesh_spmd for application to pass in topology
  test/test_torch_distributed_xla_backend.py
  torch_xla/distributed/xla_backend.py
Labels: backport_2.2

#5803 Incorporate compilation environment in hash
  torch_xla/csrc/BUILD
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/env_hash.cc
  torch_xla/csrc/runtime/env_hash.h
  torch_xla/csrc/runtime/env_hash_test.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/xla_graph_executor.cpp
Labels: backport_2.2

#5804 Enable persistent compilation caching
  test/run_tests.sh
  test/test_persistent_cache.py
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: backport_2.2

#5956 Add reduce-scatter coalescing for FSDP/ZeRO1
  test/test_mp_reduce_scatter.py
  test/test_torch_distributed_xla_backend.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/cross_replica_reduces.cpp
  torch_xla/csrc/cross_replica_reduces.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/reduce_scatter.cpp
  torch_xla/csrc/ops/reduce_scatter.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/distributed/xla_backend.py
Labels: backport_2.2

#5922 [dynamo] Move CPU tensor constructor nodes to XLA.
  test/dynamo/test_bridge.py
  torch_xla/core/dynamo_bridge.py
Labels: xla:gpu, backport_2.2

#6056 Remove redundant log message
  torch_xla/csrc/lowering_context.cpp
Labels: backport_2.2

#6060 Move CUDA tensors to CPU before moving to XLA.
  test/test_core_aten_ops.py
  torch_xla/csrc/runtime/tensor_source.h
Labels: xla:gpu, backport_2.2

#6053 [OpenXLA-pin] Update OpenXLA-pin to Nov29
  WORKSPACE
  openxla_patches/cuda_driver.diff
  setup.py
Labels: backport_2.2

#6069 Reduce benchmark experiment filename string.
  benchmarks/benchmark_experiment.py
Labels: xla:gpu

#6071 Move 0-dimensional tensors to CPU before copying to XLA.
  test/test_core_aten_ops.py
  torch_xla/csrc/tensor.cpp
Labels: xla:gpu, backport_2.2

#6039 Update Troubleshotting doc with new PT_XLA_DEBUG
  TROUBLESHOOTING.md
Labels: usability, backport_2.2

#6058 Add out-of-place reduce-scatter coalescing
  test/test_mp_reduce_scatter.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: backport_2.2

#6091 Increase delay in trace_detached test
  test/test_profiler.py
Labels: backport_2.2

#6059 Add out-of-place all-gather coalesced
  test/test_mp_all_gather.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: backport_2.2

#5930 Add Pattern Boundary Marking API
  WORKSPACE
  bazel/nlohmann_json.BUILD
  test/stablehlo/test_mark_pattern.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/mark_tensor.cpp
  torch_xla/csrc/ops/mark_tensor.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/stablehlo_composite_helper.cc
  torch_xla/csrc/runtime/stablehlo_composite_helper.h
  torch_xla/csrc/runtime/stablehlo_helper.cc
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/experimental/mark_pattern_utils.py
  torch_xla/experimental/xla_marker.py
Labels: stablehlo

#5636 Fix bug for low-precision ranges
  torch_xla/csrc/helpers.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/xla_lower_util.cpp
Labels: bug

#6097 [SPMD] Add apply_backward_optimization_barrier
  test/spmd/test_xla_sharding.py
  torch_xla/distributed/spmd/xla_sharding.py
Labels: backport_2.2

#6076 Fix model initialization.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6101 [SPMD] Allow mark_shard scalar tensors
  test/spmd/test_xla_sharding.py
  torch_xla/distributed/spmd/xla_sharding.py
Labels: backport_2.2

#6102 Uncomment test_aten_scatter_add_1
  test/test_core_aten_ops.py
Labels: core aten opset

#5946 Fix bad error message when `PjRtComputationClient` throws exception
  torch_xla/csrc/runtime/runtime.cc
Labels: runtime, backport_2.2

#6123 Handle negative dim for Diagonal Scatter
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: backport_2.2

#6104 Add flag for equal_nan in test_core_aten_ops.py
  test/test_core_aten_ops.py
Labels: core aten opset

#6105 Uncomment test_aten_isinf_2 at test_core_aten_ops.py
  test/test_core_aten_ops.py
Labels: core aten opset

#6110 Do manual type conversion for isnan op
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
Labels: core aten opset

#5936 Fix zero-1 bug for inferring local ranks
  torch_xla/distributed/zero_redundancy_optimizer.py
Labels: fsdp, backport_2.2

#6148 Don't explcitly include virtual device in hash
  test/test_persistent_cache.py
  torch_xla/csrc/runtime/pjrt_computation_client.cc
Labels: backport_2.2

#6153 [benchmarks] Collect XLA compilation and execution metrics.
  benchmarks/experiment_runner.py
Labels: xla:gpu

#6072 Remove branch on undefined variable.
  benchmarks/experiment_runner.py
Labels: xla:gpu

#6166 Promote int to float for tanh operation (consistent with Pytorch)
  test/cpp/test_aten_xla_tensor_2.cpp
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
Labels: core aten opset

#6182 Re-land: Fix model initialization.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#5644 Dynamic PJRT plugin registration API
  test/pjrt/test_dynamic_plugin_tpu.py
  test/tpu/xla_test_job.yaml
  torch_xla/_internal/pjrt.py
  torch_xla/_internal/tpu.py
  torch_xla/core/xla_env_vars.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/env_vars.cc
  torch_xla/csrc/runtime/env_vars.h
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_registry.cc
  torch_xla/csrc/runtime/pjrt_registry.h
  torch_xla/csrc/runtime/profiler.cc
  torch_xla/experimental/plugins.py
  torch_xla/runtime.py
Labels: runtime

#6202 Rename `TransferToServer` to `TransferToDevice`
  TROUBLESHOOTING.md
  docs/first_steps.md
  docs/pytorch_xla_overview.md
  test/cpp/cpp_test_util.cpp
  test/cpp/test_replication.cpp
  test/metrics_compare_utils_test.py
  test/pjrt/test_metrics.py
  test/pjrt/test_profiler.py
  test/spmd/test_xla_virtual_device.py
  test/test_metrics.py
  test/test_operations.py
  test/test_profiler.py
  torch_xla/csrc/device.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.cc
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client_test.cc
  torch_xla/csrc/runtime/metrics_analysis.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client_test.cc
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/tensor_util.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/debug/metrics.py
Labels: runtime

#6168 Add default v5 flags
  torch_xla/__init__.py
Labels: backport_2.2

#6211 Update dtype conversion for aten_tan
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
Labels: core aten opset

#6213 Add manual type conversion for aten_asin
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
Labels: core aten opset

#6222 Enable core aten test and loose tolerance for aten_log10 and aten_log2
  test/test_core_aten_ops.py
Labels: core aten opset

#6224 Promote int to float for acos operation (consistent with Pytorch)
  test/cpp/test_aten_xla_tensor_2.cpp
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
Labels: core aten opset

#6203 Create sharded data placeholders directly
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/xla_sharding_util.cpp
Labels: runtime
