Repository pytorch/xla, pull requests merged in 2023-03, with the labels that each got.

#4709 [PJRT] Remove start method from `_run_singleprocess`
  test/pjrt/test_experimental_pjrt_tpu.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4710 Lower UpsampleBilinear/Nearest2DBackward with scale factor on TPU
  test/cpp/test_aten_xla_tensor.cpp
  torch_xla/csrc/aten_xla_type.cpp
Labels: op lowering

#4712 [PJRT] Cherry pick local rank changes to r2.0 release
  test/pjrt/test_experimental_pjrt_tpu.py
  third_party/xla_client/env_vars.cc
  third_party/xla_client/env_vars.h
  third_party/xla_client/pjrt_computation_client.cc
  torch_xla/core/xla_env_vars.py
  torch_xla/experimental/pjrt.py
Labels: runtime

#4158 Functionalization integration
  test/cpp/run_tests.sh
  test/cpp/test_aten_xla_tensor.cpp
  test/dynamo/test_dynamo.py
  test/pytorch_test_base.py
  test/spmd/test_xla_virtual_device.py
  test/test_dynamic_shapes.py
  test/test_operations.py
  torch_patches/.torch_pin
  torch_xla/csrc/aten_cpu_fallback.cpp
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/dynamic_ir.cpp
  torch_xla/csrc/ops/dynamic_ir.h
  torch_xla/csrc/ops/index_ops.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/tensor_util.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
  torch_xla/distributed/xla_backend.py
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4706 Update API GUIDE to include multi host training and add some colors
  API_GUIDE.md
Labels: documentation

#4722 Manually track type of SymNode
  test/cpp/test_aten_xla_tensor.cpp
  test/cpp/test_symint.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_impl.cpp
Labels: REMOVE_TORCH_PIN

#4723 [PJRT] Replace XRT CI tests with PJRT
  .circleci/common.sh
  test/run_tests.sh
Labels: runtime

#4721 [SPMD] Preserve parameter sharding with output data sharding
  test/cpp/test_xla_sharding.cpp
  test/spmd/test_xla_sharding.py
  third_party/xla_client/computation_client.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
  third_party/xla_client/xrt_computation_client.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/device_data.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: SPMD

#4664 [FSDP] Add meta device and torchdistx deferred_init feature in FSDP
  test/run_tests.sh
  test/test_torch_distributed_fsdp_meta.py
  torch_xla/distributed/fsdp/_init_utils.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
Labels: fsdp

#4734 Update README
  README.md
Labels: documentation

#4693 Add feature to increase the number of host to device transfer threads
  test/test_train_mp_imagenet.py
  torch_xla/distributed/parallel_loader.py
Labels: perf

#4744 Add public readme for torchdynamo
  docs/dynamo.md
  docs/source/index.rst
Labels: documentation

#4743 [PJRT] Update `torch.distributed` unit test to use PJRT
  test/run_tests.sh
  test/test_torch_distributed_xla_backend.py
Labels: runtime

#4752 Jack cao g/r20 backportdoc
  API_GUIDE.md
  README.md
  docs/dynamo.md
  docs/source/index.rst
Labels: documentation

#4433 Remove a dynamic shape related comment that doesn't hold anymore.
  test/cpp/run_tests.sh
  test/cpp/test_aten_xla_tensor.cpp
Labels: dynamism

#4757 [PJRT] Update pjrt.md for new release
  docs/pjrt.md
Labels: runtime

#4780 Add detail about PJRT performance to `pjrt.md`
  docs/assets/torchbench_pjrt_vs_xrt.svg
  docs/assets/torchbench_tfrt_vs_se.svg
  docs/pjrt.md
Labels: runtime

#4808 [SPMD] asynchronous data loading with ParallelLoader
  test/spmd/test_train_spmd_imagenet.py
  test/spmd/test_train_spmd_linear_model.py
  torch_xla/core/xla_model.py
  torch_xla/distributed/parallel_loader.py
  torch_xla/experimental/xla_sharding.py
Labels: SPMD

#4816 Apply gradient checkpointing to spmd ResNet benchmarking script
  test/spmd/test_train_spmd_imagenet.py
  test/spmd/test_train_spmd_linear_model.py
Labels: SPMD

#4724 Catch info from metadata
  test/pjrt/test_experimental_tpu.py
  torch_xla/experimental/tpu.py
Labels: DO_NOT_MERGE_YET
