Repository pytorch/xla, pull requests merged in 2023-01, with the labels that each got.

#4390 [SPMD] Use sharding annotation from XLATensor data as ground truth.
  test/test_xla_sharding.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/xla_graph_executor.cpp
Labels: SPMD

#4422 Rotate GITHUB_TORCH_XLA_BOT_TOKEN and use a new account
  .circleci/config.yml
  .circleci/doc_push.sh
Labels: cleanup

#4427 Fix nightly whl build issue & introduce new knobs in cloudbuild.yaml
  docker/Dockerfile
  docker/cloudbuild.yaml
  scripts/build_torch_wheels.sh
Labels: cleanup

#4425 Make dyanmo execute async
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: dynamo

#4322 Add dynamic shape support to sigmoidbackward
  test/test_dynamic_shape_models.py
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
Labels: dynamism

#4446 Reenable CPP tests in whl build
  docker/Dockerfile
  docker/cloudbuild.yaml
  docker/common.sh
Labels: cleanup

#4445 Add unit test for dynamo+training for pytorch/xla
  test/dynamo/test_dynamo.py
Labels: dynamo

#4449 Codegen LeakyRelu and partially codegen LeakyReluBackward
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/leaky_relu.cpp
  torch_xla/csrc/ops/leaky_relu.h
  torch_xla/csrc/ops/leaky_relu_backward.cpp
  torch_xla/csrc/ops/leaky_relu_backward.h
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  xla_native_functions.yaml
Labels: codegen

#4460 Allow /dev/shm as sandboxed build base with /tmp as default
  build_torch_xla_libs.sh
  docker/Dockerfile
  docker/cloudbuild.yaml
  docker/experimental/Dockerfile
Labels: cleanup

#4447 Code-gen addcdiv again
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  xla_native_functions.yaml
Labels: REMOVE_TORCH_PIN

#4400 Enable PJRT C API with `libtpu-nightly`
  test/pjrt/test_experimental_pjrt_tpu.py
  third_party/xla_client/env_vars.cc
  third_party/xla_client/env_vars.h
  third_party/xla_client/pjrt_computation_client.cc
  third_party/xla_client/pjrt_computation_client.h
Labels: runtime

#4476 refactor: move dynamo/TorchXLA bridge to pytorch/xla repo
  test/dynamo/test_bridge.py
  test/dynamo/test_num_output.py
  test/run_tests.sh
  torch_xla/core/dynamo_bridge.py
Labels: dynamo

#4507 Disable more dynamic shape tests
  test/run_tests.sh
Labels: dynamism

#4487 Fix HLO dump file names for PJRT
  test/pjrt/test_experimental_pjrt_multi_cpu.py
  third_party/xla_client/sys_util.cc
  third_party/xla_client/sys_util.h
  torch_xla/csrc/debug_util.cpp
Labels: runtime

#4503 [PJRT] Don't use futures on `ExecuteSharded` output buffers
  third_party/xla_client/pjrt_computation_client.cc
Labels: runtime

#4504 [PJRT] Release the GIL during `TransferFromServer`
  configuration.yaml
  torch_xla/csrc/xla_graph_executor.cpp
Labels: runtime

#4520 [PJRT] Experimental support for `torch.distributed` and DDP on TPU v2/v3
  test/distributed_util.py
  test/pjrt/test_ddp.py
  test/pjrt/test_train_pjrt_imagenet.py
  test/pjrt/test_train_pjrt_mnist.py
  test/test_train_mp_imagenet.py
  test/test_train_mp_mnist.py
  torch_xla/experimental/pjrt.py
  torch_xla/experimental/pjrt_backend.py
Labels: runtime

#4523 Optimize Dynamo Training Execute
  test/dynamo/test_num_output.py
  torch_xla/core/dynamo_bridge.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: dynamo

#4540 Disable test_view_copy_out_xla
  test/pytorch_test_base.py
Labels: bug
