Repository pytorch/xla, pull requests merged in 2024-10, with the labels that each got.

#8207 Fix warning messages when using fsdpv2
  torch_xla/distributed/fsdp/utils.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
Labels: tpuci

#8209 [export] Conditionally load decomp table
  torch_xla/stablehlo.py
Labels: stablehlo

#8062 change r2.5 to use jax stable version 0.4.33
  setup.py
Labels: tpuci, 2.5 release

#8219 Update cuda_deps.yaml for r2.5
  infra/ansible/config/cuda_deps.yaml
Labels: 2.5 release

#8205 Raise error when minibatch is used in SPMD dataloading and per host b…
  test/spmd/test_xla_sharding.py
  torch_xla/core/xla_model.py
Labels: SPMD / Distributed, tpuci

#8265 Add peak_bytes_used to the get_memory_info
  test/pjrt/test_runtime_tpu.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
Labels: tpuci

#8273 add dist op doc
  docs/source/_static/img/dist_op_stack.png
  docs/source/features/distop.md
Labels: documentation

#8274 [cherrypick] add dist op doc (#8273)
  docs/_static/img/dist_op_stack.png
  docs/distop.md
Labels: documentation, 2.5 release

#8272 Update artifacts.auto.tfvars for 2.5.0 final wheel
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
Labels: 2.5 release

#8277 Update collective op doc based on feedback
  docs/distop.md
Labels: documentation, backport_2.5

#8267 Update XLA pin to 10/16
  .github/scripts/run_tests.sh
  WORKSPACE
  setup.py
  test/cpp/BUILD
  torch_xla/csrc/BUILD
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/matrix.cpp
  torch_xla/csrc/ops/embedding_bag.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/qr.cpp
  torch_xla/csrc/ops/randperm.cpp
  torch_xla/csrc/pooling.cpp
  torch_xla/csrc/random.cpp
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/runtime.cc
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_op_builder.cpp
  torch_xla/csrc/xla_sharding_util.cpp
Labels: tpuci

#8311 [OpenXLA/libtpu pin Update] Update to Oct20
  WORKSPACE
  setup.py
Labels: tpuci

#8328 Extend paged attention to support query_len>1
  test/test_pallas.py
  test/test_tpu_paged_attention_kernel.py
  test/tpu/run_tests.sh
  torch_xla/experimental/custom_kernel.py
  torch_xla/experimental/pallas_kernels/__init__.py
  torch_xla/experimental/pallas_kernels/multi_queries_paged_attention_kernel.py
Labels: tpuci
