Repository pytorch/xla, pull requests merged in 2024-05, with the labels that each got.

#6943 [Pallas] Support segment ids in flash attention
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7006 Expose python unsafe buffer pointer
  test/test_operations.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/unwrap_data.h
Labels: tpuci

#7020 Update XLA/JAX/libtpu pins to 2024/05/02
  WORKSPACE
  setup.py
Labels: tpuci

#7022 Update non_xla attention to properly support paged_attention dynamo code path
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#6940 Adding megablox gmm standalone
  test/test_megablox.py
  test/tpu/run_tests.sh
  torch_xla/experimental/megablox/__init__.py
  torch_xla/experimental/megablox/common.py
  torch_xla/experimental/megablox/gmm.py
Labels: pallas, tpuci

#7044 [FSDPv2] Support MultiSlice
  test/spmd/test_fsdp_v2.py
  test/tpu/run_tests.sh
  torch_xla/experimental/spmd_fully_sharded_data_parallel.py
Labels: tpuci

#7045 [Pallas] Add test_pallas_spmd.py to tpu ci
  test/tpu/run_tests.sh
Labels: tpuci

#7046 Add option to export FX Node metadata to StableHLO
  test/stablehlo/test_mlir_debuginfo.py
  torch_xla/experimental/xla_mlir_debuginfo.py
  torch_xla/stablehlo.py
Labels: stablehlo

#7052 Pin update 20240513
  WORKSPACE
  setup.py
  test/stablehlo/test_pt2e_qdq.py
  torch_xla/csrc/reduction.cpp
Labels: tpuci

#7058 Update runner and runner-container-hooks versions
  test/tpu/Dockerfile
Labels: tpuci

#7060 Support megacore_mode in paged_attention
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7067 [benchmarks] Fix AMP setup for torchbench models.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#7068 Add `xla.step` context manager
  README.md
  test/test_devices.py
  torch_xla/torch_xla.py
Labels: runtime

#7080 [benchmarks] Add default value to `move_to_device`.
  benchmarks/util.py
Labels: xla:gpu

#7081 Fix overflow for `div` arguments.
  test/cpp/test_aten_xla_tensor_4.cpp
  torch_xla/csrc/tensor_methods.cpp
Labels: xla:gpu

#7086 Implement `ComputationClient::GetMemoryInfo`
  test/pjrt/test_runtime_tpu.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
Labels: usability, tpuci

#7090 Add data-type promotion to `gelu_backward`.
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: xla:gpu

#7099 [Pallas] Refactor the gmm kernel
  test/test_megablox.py
  torch_xla/experimental/custom_kernel.py
  torch_xla/experimental/megablox/__init__.py
  torch_xla/experimental/megablox/common.py
  torch_xla/experimental/megablox/gmm.py
Labels: tpuci

#7091 Add data-type promotion to `stack`.
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: xla:gpu

#7107 [Pallas] Introduce _make_group_metadata
  test/test_gmm.py
  test/tpu/run_tests.sh
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7117 [Pallas] Make gmm functional
  test/test_gmm.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7119 [Pallas] Set a better tiling for gmm
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7113 `index`: fix index of 0-element tensor by 0-element tensor.
  test/test_operations.py
  torch_xla/csrc/ops/index_ops.cpp
Labels: xla:gpu

#7121 [MoE] Test sorting lhs for gmm
  test/test_gmm.py
Labels: tpuci

#7133 [Pallas] Make gmm support bf16
  test/test_gmm.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7134 [FSDPv2] Shard on the maximal dim of weights
  test/spmd/test_fsdp_v2.py
  torch_xla/experimental/spmd_fully_sharded_data_parallel.py
Labels: tpuci

#7116 Add function for retrieving fallback operations.
  test/test_metrics.py
  torch_xla/core/dynamo_bridge.py
  torch_xla/csrc/aten_cpu_fallback.cpp
  torch_xla/csrc/aten_cpu_fallback.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/debug/metrics.py
Labels: xla:gpu

#7137 [Pallas] Support tgmm
  test/test_gmm.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7142 Revert "`upsample_bilinear`: fix output data-type."
  test/test_operations.py
  torch_xla/csrc/resize_ops.cpp
Labels: tpuci

#7145 [Pallas] Make repeat_with_fixed_output_size not OOM on VMEM
  test/test_gmm.py
  test/test_operations.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7152 [Pallas] Introduce GMM(torch.autograd.Function)
  test/test_gmm.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7019 [Doc] Update spmd.md for doc
  docs/spmd.md
Labels: documentation
