Repository pytorch/xla, pull requests merged in 2024-02, with the labels that each got.

#6434 Disambiguate `benchmarks` directory search.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6407 Check precision only if on CUDA and not inductor.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6070 Enable CUDA support for PyTorch on CI.
  .circleci/build.sh
Labels: xla:gpu

#6160 Move tests that need CUDA to `test_operations.py`.
  test/test_core_aten_ops.py
  test/test_operations.py
Labels: xla:gpu

#6448 Re-instate the missing CPU CI tests and their coverage reports
  .github/workflows/_test.yml
Labels: bug, CI

#6446 Add `benchmarks/dynamo` search option for finding PyTorch skip file.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6447 [benchmarks] Add support for AMP execution.
  benchmarks/experiment_runner.py
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6433 Force guards when performing boolean operations on XLASymNode
  torch_xla/csrc/tensor.cpp
Labels: dynamism

#6469 Add process group documentation for SPMD
  docs/spmd.md
Labels: documentation

#6484 [benchmarks] Add `no-skip` argument.
  benchmarks/experiment_runner.py
Labels: xla:gpu

#6491 [benchmarks] Remove `--strict-compatible` argument.
  benchmarks/experiment_runner.py
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6509 [benchmarks] Increase compilation cache.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6515 [SPMD] input sharding for both train & test data loading in imagenet example
  test/spmd/test_train_spmd_imagenet.py
Labels: SPMD

#6512 [benchmarks] Fix execution with AMP precision.
  benchmarks/benchmark_model.py
  benchmarks/experiment_runner.py
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6507 Lowering for _pdist_forward
  codegen/xla_native_functions.yaml
  test/cpp/test_aten_xla_tensor_6.cpp
  test/test_core_aten_ops.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
Labels: core aten opset

#6518 [benchmarks] Default to `bfloat16` (inference) and AMP (training) precision.
  benchmarks/benchmark_model.py
  benchmarks/torchbench_model.py
  benchmarks/util.py
Labels: xla:gpu

#6550 [benchmarks] Fix AMP data-type.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6558 [benchmarks] Update `DENY_LIST`.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6571 Add basic device APIs to the top-level `torch_xla` module.
  test/run_tests.sh
  test/test_devices.py
  torch_xla/__init__.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/torch_xla.py
Labels: runtime, usability

#6532 [Fori_loop|While_loop] Placeholder lower torch.while_loop with python dispatch for simple addition test case
  .github/workflows/tpu_ci.yml
  test/run_tests.sh
  test/test_fori_loop_with_while_loop_simple_add_dispatch_in_torch.py
  test/tpu/xla_test_job.yaml
  torch_xla/experimental/fori_loop.py
Labels: fori_loop

#6612 [benchmarks] Set autocast kwargs only if AMP.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6632 [benchmarks] Small fixes for benchmarking script.
  benchmarks/torchbench_model.py
  benchmarks/util.py
Labels: xla:gpu
