Repository pytorch/xla, pull requests merged in 2024-03, with the labels that each got.

#6657 [OpenXLA|TSL] Replace `tsl/platform/stringpiece.h` with `absl/strings/string_view.h`
  torch_xla/csrc/convolution_helper.cpp
  torch_xla/csrc/convolution_helper.h
Labels: tsl

#6652 [SPMD] Check the real physical device type if XlaDeviceType::SPMD
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/data_ops.cpp
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
  torch_xla/csrc/layout_manager.cpp
  torch_xla/csrc/resize_ops.cpp
  torch_xla/csrc/xla_lower_util.cpp
Labels: SPMD

#6686 Change ATEN generator argument type to const std::optional<Generator>&
  torch_xla/csrc/aten_xla_type.cpp
Labels: REMOVE_TORCH_PIN

#6683 [SPMD][DTensor] introduce xla_distribute_module for DTensor integration
  test/run_tests.sh
  test/spmd/test_dtensor_integration.py
  torch_xla/distributed/spmd/api.py
Labels: SPMD

#6655 [OpenXLA|TSL] Replace tsl::Status to absl::Status in profiler.h/.cc
  torch_xla/csrc/convolution_helper.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/ifrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_registry.cc
  torch_xla/csrc/runtime/profiler.cc
  torch_xla/csrc/runtime/profiler.h
  torch_xla/csrc/runtime/tf_logging.h
Labels: tsl

#6603 [Fori_loop|While_loop] Enable fori_loop with add/sub test case
  test/test_fori_loop_with_while_loop_simple_add_dispatch_in_torch.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/lowering_context.h
  torch_xla/experimental/fori_loop.py
Labels: fori_loop

#6680 Make use_spmd to force SPMD mode for easier 3rd-party integration.
  test/spmd/test_xla_spmd_python_api_interaction.py
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/runtime.py
Labels: SPMD

#6712 [SPMD] Rename conflicting test class names
  test/spmd/test_spmd_graph_dump.py
  test/spmd/test_xla_sharding.py
  test/spmd/test_xla_sharding_hlo.py
Labels: SPMD

#6705 Ignore .vscode/ and move settings.json as template
  .gitignore
  contrib/vscode/settings.json
Labels: cleanup

#6720 [SPMD] Remove unused spmd partitioning debugging tool.
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: SPMD

#6718 Allow `int` data-type for `Embedding` indices.
  test/test_operations.py
  torch_xla/csrc/tensor_ops.cpp
Labels: xla:gpu

#6726 Add IsVirtualDeivce() and refactor
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/device_data.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
Labels: SPMD, backport_2.3

#6677 Pin update March 2024
  .bazelversion
  .circleci/common.sh
  WORKSPACE
  openxla_patches/quant_dequant_converter.diff
  setup.py
  torch_xla/csrc/ops/dequant_tensor.cpp
  torch_xla/csrc/ops/quant_tensor.cpp
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/profiler.cc
Labels: backport_2.3

#6723 [SPMD] Use UNKNOWN sharding type for implicit replication
  .circleci/common.sh
  .kokoro/common.sh
  test/cpp/test_xla_sharding.cpp
  test/spmd/test_xla_sharding.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/debug_util.cpp
  torch_xla/csrc/ir.cpp
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: SPMD, backport_2.3

#6738 fix csv output error (#6662)
  benchmarks/result_analyzer.py
Labels: backport_2.3

#6734 [r2.3] backport #6723
  .circleci/common.sh
  .kokoro/common.sh
  test/cpp/test_xla_sharding.cpp
  test/spmd/test_xla_sharding.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/debug_util.cpp
  torch_xla/csrc/ir.cpp
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_util.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: backport_2.3

#6713 [Pallas] Introduce make_kernel_from_pallas
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: backport_2.3

#6719 [SPMD] auto-sharding PoC
  docs/spmd.md
  test/run_tests.sh
  test/spmd/args_parse.py
  test/spmd/test_dtensor_integration.py
  test/spmd/test_dtensor_integration2.py
  test/spmd/test_dynamo_spmd.py
  test/spmd/test_spmd_graph_dump.py
  test/spmd/test_train_spmd_imagenet.py
  test/spmd/test_train_spmd_linear_model.py
  test/spmd/test_xla_auto_sharding.py
  test/spmd/test_xla_distributed_checkpoint.py
  test/spmd/test_xla_sharding.py
  test/spmd/test_xla_sharding_base.py
  test/spmd/test_xla_sharding_hlo.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  test/spmd/test_xla_virtual_device.py
  test/test_train_mp_imagenet.py
  test/tpu/run_tests.sh
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/distributed/spmd/__init__.py
  torch_xla/distributed/spmd/api.py
  torch_xla/distributed/spmd/xla_sharding.py
  torch_xla/runtime.py
Labels: SPMD, backport_2.3

#6755 [r2.3] backport: auto-sharding PoC (#6719)
  docs/spmd.md
  test/run_tests.sh
  test/spmd/args_parse.py
  test/spmd/test_dtensor_integration.py
  test/spmd/test_dtensor_integration2.py
  test/spmd/test_dynamo_spmd.py
  test/spmd/test_spmd_graph_dump.py
  test/spmd/test_train_spmd_imagenet.py
  test/spmd/test_train_spmd_linear_model.py
  test/spmd/test_xla_auto_sharding.py
  test/spmd/test_xla_distributed_checkpoint.py
  test/spmd/test_xla_sharding.py
  test/spmd/test_xla_sharding_base.py
  test/spmd/test_xla_sharding_hlo.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  test/spmd/test_xla_virtual_device.py
  test/test_train_mp_imagenet.py
  test/tpu/run_tests.sh
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
  torch_xla/distributed/spmd/__init__.py
  torch_xla/distributed/spmd/api.py
  torch_xla/distributed/spmd/xla_sharding.py
  torch_xla/runtime.py
Labels: backport_2.3

#6753 Include auto-sharding configs as part of hash
  test/spmd/test_xla_auto_sharding.py
  torch_xla/csrc/xla_graph_executor.cpp
Labels: SPMD, backport_2.3

#6746 Disable coverage temporarily
  .github/workflows/build_and_test.yml
Labels: DO_NOT_REVIEW_YET

#6763 [r2.3] Include auto-sharding configs as part of hash (#6753)
  test/spmd/test_xla_auto_sharding.py
  torch_xla/csrc/xla_graph_executor.cpp
Labels: backport_2.3

#6757 remove openxla_eval from the doc
  docs/dynamo.md
Labels: backport_2.3

#6745 Fix type promotion for `pow`.
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: xla:gpu

#6697 Re-land: Make `as_strided_copy` materialize a new tensor with `index`.
  test/test_operations.py
  test/test_ops.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: xla:gpu

#6747 [Pallas] Introduce jax_import_guard
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: backport_2.3

#6748 [Pallas] Add a bfloat16 flash attention test case
  test/test_pallas.py
Labels: backport_2.3

#6653 Add fx passes to support exporting unbounded dynamism
  test/run_tests.sh
  test/stablehlo/test_export_fx_passes.py
  test/stablehlo/test_mark_pattern.py
  test/stablehlo/test_pt2e_qdq.py
  test/stablehlo/test_saved_model.py
  test/stablehlo/test_unbounded_dynamism.py
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/dynamic_expand.cpp
  torch_xla/csrc/ops/dynamic_expand.h
  torch_xla/csrc/ops/dynamic_view.cpp
  torch_xla/csrc/ops/dynamic_view.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/experimental/unbounded_dynamism_export.py
  torch_xla/experimental/xla_dynamic_reshape_ops.py
  torch_xla/stablehlo.py
  torch_xla/utils/stablehlo_test_utils.py
Labels: dynamism

#6773 Address deprecation in torch.distributed.checkpoint
  docs/spmd.md
  test/spmd/test_xla_distributed_checkpoint.py
  torch_xla/experimental/distributed_checkpoint/manager.py
Labels: backport_2.3

#6770 [SPMD] auto-construct auto-sharding mesh ids
  WORKSPACE
  openxla_patches/quant_dequant_converter.diff
  setup.py
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: SPMD, backport_2.3

#6777 Add dynamism support to conv1d, view, softmax
  test/stablehlo/export_vit_unbounded_dynamism.py
  test/stablehlo/export_wav2vec2.py
  test/stablehlo/test_export_fx_passes.py
  test/stablehlo/test_unbounded_dynamism.py
  torch_xla/csrc/data_ops.cpp
  torch_xla/csrc/data_ops.h
  torch_xla/csrc/ops/view.cpp
  torch_xla/csrc/softmax_builder.cpp
  torch_xla/experimental/unbounded_dynamism_export.py
Labels: dynamism

#6782 [SPMD] auto-construct auto-sharding mesh ids (#6770)
  WORKSPACE
  openxla_patches/quant_dequant_converter.diff
  setup.py
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
  torch_xla/csrc/xla_sharding_util.h
Labels: backport_2.3

#4690 Fix preserve_rng_state for activation checkpointing
  test/test_operations.py
  torch_xla/core/xla_model.py
  torch_xla/utils/checkpoint.py
Labels: fsdp, backport_2.3

#6785 [Pallas] Make a FlashAttention Wrapper
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: backport_2.3

#6781 Add dynamism support to `aten.embedding` and `aten.split_with_sizes`
  test/stablehlo/test_export_fx_passes.py
  test/stablehlo/test_unbounded_dynamism.py
  torch_xla/experimental/unbounded_dynamism_export.py
Labels: dynamism

#6789 Use stablehlo.composite instead of stablehlo.custom_call
  test/stablehlo/test_mark_pattern.py
  torch_xla/csrc/runtime/stablehlo_composite_helper.cc
Labels: stablehlo

#6783 Add patch for unbounded dynamism
  WORKSPACE
  openxla_patches/unbounded_dynamism.diff
  test/stablehlo/test_unbounded_dynamism.py
Labels: dynamism

#6792 [Pallas] Allow setting FlashAttention's causal mask
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: backport_2.3

#6025 ZeRO1: Add bucketting logic to control the size of tensors for all-gather/reduce-scatter
  test/test_mp_all_gather.py
  test/test_mp_reduce_scatter.py
  torch_xla/core/xla_model.py
  torch_xla/distributed/zero_redundancy_optimizer.py
Labels: backport_2.2, backport_2.3

#6797 Update XLA pin
  WORKSPACE
  openxla_patches/unbounded_dynamism.diff
  setup.py
Labels: openxla, backport_2.3

#6802 Make compile count in Dynamo test more general
  test/dynamo/test_dynamo.py
  torch_patches/.torch_pin
Labels: REMOVE_TORCH_PIN

#6795 Install torchvision in release docker
  infra/ansible/Dockerfile
Labels: backport_2.3

#6805 Add missing shape metadata for the last replaced fx node
  test/stablehlo/export_tinyroberta_unbounded_dynamism.py
  test/stablehlo/test_export_fx_passes.py
  torch_xla/experimental/unbounded_dynamism_export.py
  torch_xla/experimental/xla_dynamic_reshape_ops.py
Labels: dynamism

#6817 [Pallas] Support XLA_USE_BF16
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: backport_2.3

#6826 [Pallas] Set the major-minor layout for inputs and outputs
  configuration.yaml
  test/test_pallas.py
  torch_xla/csrc/layout_manager.cpp
  torch_xla/csrc/xla_lower_util.cpp
Labels: backport_2.3

#6846 [SPMD] use UNKNOWN as default sharded data sharding type only for auto-sharding
  test/spmd/test_xla_sharding.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
Labels: SPMD

#6840 Support array attribute in stablehlo composite
  test/stablehlo/test_mark_pattern.py
  torch_xla/csrc/runtime/stablehlo_composite_helper.cc
  torch_xla/experimental/xla_marker.py
Labels: stablehlo

#6852 [r2,3][SPMD] use UNKNOWN as default sharded data sharding type selectively
  test/spmd/test_xla_sharding.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_sharding_util.cpp
Labels: backport_2.3
