Repository pytorch/xla, pull requests merged in 2024-06, with the labels that each got.

#7164 Unify how we use torch commit in the CI.
  .github/workflows/_get_torch_commit.yml
  .github/workflows/_test.yml
  .github/workflows/_test_requiring_torch_cuda.yml
  .github/workflows/build_and_test.yml
Labels: CI

#7130 `mul`: convert inputs to result type.
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/init_python_bindings.cpp
Labels: xla:gpu

#7172 Run some of the examples in TPU CI
  test/tpu/run_tests.sh
Labels: tpuci

#7168 Re-land: `upsample_bilinear`: fix output data-type.
  test/test_operations.py
  torch_xla/csrc/resize_ops.cpp
Labels: xla:gpu, tpuci

#7195 Update images to support dark mode
  docs/assets/IRgraph_markstep.png
  docs/assets/IRgraph_no_markstep.png
  docs/assets/pytorchXLA_flow.svg
  docs/assets/spmd_debug_1_light.png
  docs/assets/spmd_debug_2_light.png
  docs/spmd.md
Labels: docathon-h1-2024, easy

#7202 [Pallas] Make _histogram output int32
  test/test_gmm.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7200 openxla pin update to 06/05
  WORKSPACE
  setup.py
Labels: openxla, tpuci

#7206 Let grad ckpt apply opt-barrier to all params and buffers
  test/test_operations.py
  torch_xla/utils/checkpoint.py
Labels: tpuci

#6798 Triton
  .github/workflows/_build_torch_with_cuda.yml
  test/test_triton.py
  torch_xla/csrc/BUILD
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/gpu_custom_call.cpp
  torch_xla/csrc/ops/gpu_custom_call.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  torch_xla/experimental/triton.py
Labels: Triton

#7201 Add int8 per channel weight-only quantized matmul
  docs/quantized_ops.md
  test/quantized_ops/test_quantized_matmul.py
  test/run_tests.sh
  torch_xla/experimental/xla_quantized_matmul.py
Labels: Quantization

#7214 init glossary
  docs/glossry.md
Labels: docathon-h1-2024, easy

#7207 Remove stack dump for compiler failure which can happen often
  torch_xla/csrc/runtime/debug_macros.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
Labels: usability

#7162 torchbench CI
  .github/scripts/run_tests.sh
  benchmarks/benchmark_experiment.py
  test/benchmarks/run_torchbench_tests.sh
Labels: CI

#7235 Support int4 weight in quantized matmul/linear
  docs/quantized_ops.md
  test/quantized_ops/test_quantized_matmul.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/cast_int4.cpp
  torch_xla/csrc/ops/cast_int4.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/experimental/xla_quantized_matmul.py
Labels: Quantization

#7234 Enable eager mode for PyTorch/XLA
  docs/source/index.rst
  examples/eager/train_decoder_only_eager.py
  test/debug_tool/test_pt_xla_debug.py
  test/test_metrics.py
  test/tpu/run_tests.sh
  torch_xla/csrc/debug_util.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.cc
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
  torch_xla/experimental/__init__.py
  torch_xla/experimental/eager.py
Labels: usability, tpuci

#7219 Register custom call with CUDA plugin
  .github/workflows/_build_plugin.yml
  .github/workflows/_build_torch_with_cuda.yml
  .github/workflows/_test_requiring_torch_cuda.yml
  .github/workflows/build_and_test.yml
  torch_xla/csrc/BUILD
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
Labels: Triton

#7246 add torch_xla.experimental.compile for eager mode
  docs/source/index.rst
  examples/eager/train_decoder_only_eager_with_compile.py
  examples/train_decoder_only_base.py
  test/eager/test_eager_with_xla_compile.py
  test/tpu/run_tests.sh
  torch_xla/experimental/__init__.py
  torch_xla/experimental/eager.py
Labels: usability

#7254 Update the XLA pin
  WORKSPACE
  setup.py
Labels: tpuci

#7268 Enable PJRT plugins by default
  torch_xla/__init__.py
  torch_xla/_internal/tpu.py
  torch_xla/csrc/init_python_bindings.cpp
Labels: runtime, usability, tpuci

#7271 Revert the mul change
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: backport_2.4

#7208 Updated the examples folder readme file
  examples/README.md
Labels: docathon-h1-2024, medium

#7273 Update docs/gpu.md
  docs/gpu.md
Labels: docathon-h1-2024, medium

#7248 [SPMD] Fix reduce_scatter for TPUv2
  test/spmd/test_xla_sharding.py
Labels: tpuci, backport_2.4

#7272 Create common `setup` action to wrap setup steps
  .github/workflows/_build_plugin.yml
  .github/workflows/_build_torch_with_cuda.yml
  .github/workflows/_build_torch_xla.yml
  .github/workflows/_get_torch_commit.yml
  .github/workflows/_test.yml
  .github/workflows/_test_requiring_torch_cuda.yml
  .github/workflows/_tpu_ci.yml
  .github/workflows/build_and_test.yml
  .github/workflows/setup/action.yml
Labels: tpuci

#7278 Avoid log spam
  torch_xla/csrc/runtime/pjrt_registry.cc
Labels: backport_2.4

#7277 Document process to create a new PJRT plugin
  docs/plugins.md
  plugins/cpu/README.md
  plugins/cpu/pyproject.toml
  plugins/cuda/README.md
Labels: runtime, documentation

#7264 Make a dynamo inference test that runs on TPU
  test/dynamo/test_dynamo.py
Labels: dynamo, tpuci

#7283 Refactor SPMD docs
  docs/source/index.rst
  docs/spmd.md
  docs/spmd_advanced.md
  docs/spmd_basic.md
  docs/spmd_distributed_checkpoint.md
Labels: documentation

#7279 Use default github token for docs preview
  .github/workflows/_docs.yml
Labels: DO_NOT_MERGE, DO_NOT_REVIEW_YET

#7284 Avoid log spam (#7278)
  torch_xla/csrc/runtime/pjrt_registry.cc
Labels: backport_2.4

#7285 Revert the mul change (#7271)
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: backport_2.4

#7257 [benchmarks] Initialize `moco` and TPU experiments on XLA.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#7308 Update XLA Pin
  WORKSPACE
  setup.py
Labels: tpuci

#7315 only run eager test on v4 CI
  examples/decoder_only_model.py
  test/tpu/run_tests.sh
Labels: tpuci

#7322 Egaerly execute inplace ops if in eager mode
  test/eager/test_eager.py
  test/run_tests.sh
  torch_xla/csrc/tensor.cpp
Labels: usability, eager

#7321 Initialize benchmarks with device type.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#7244 Update cuda_deps.yaml to include CUDA 12.4
  infra/ansible/config/cuda_deps.yaml
Labels: backport_2.4

#7327 Support eager mode for multi-process training
  examples/eager/train_decoder_only_eager_multi_process.py
  examples/train_decoder_only_base.py
  test/eager/test_eager_all_reduce_in_place.py
  test/run_tests.sh
  test/tpu/run_tests.sh
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
Labels: usability, tpuci, eager

#7340 torch_xla.manual_seed
  docs/source/index.rst
  test/test_operations.py
  torch_xla/torch_xla.py
Labels: usability

#7328 Handle random seed for eager mode
  test/eager/test_eager.py
  torch_xla/csrc/xla_graph_executor.cpp
Labels: eager

#7477 [SPMD] Expose apply_backward_optimization_barrier
  torch_xla/distributed/spmd/__init__.py
Labels: backport_2.4

#7576 [SPMD] Support manual all-reduce
  test/spmd/test_xla_sharding.py
  torch_xla/csrc/cross_replica_reduces.cpp
  torch_xla/csrc/cross_replica_reduces.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/all_reduce.cpp
  torch_xla/csrc/ops/all_reduce.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: backport_2.4

#7337 tests for tpu-info CLI
  test/tpu/run_tests.sh
  test/tpu/tpu_info/requirements.txt
  test/tpu/tpu_info/test_cli.py
Labels: usability, tpuci

#7341 Enable eager spmd
  examples/eager/train_decoder_only_eager_spmd_data_parallel.py
  test/eager/test_eager_spmd.py
  test/run_tests.sh
  test/tpu/run_tests.sh
  torch_xla/csrc/aten_xla_type.cpp
Labels: SPMD, eager

#7579 Clean up experimental
  test/pjrt/test_profiler.py
  torch_xla/experimental/gpu.py
  torch_xla/experimental/pjrt.py
  torch_xla/experimental/tpu.py
Labels: usability
