Repository pytorch/xla, pull requests merged in 2024-01, with the labels that each got.

#6197 Remove obsolete device special cases
  test/pjrt/test_dtypes.py
  test/run_tests.sh
  test/tpu/xla_test_job.yaml
  torch_xla/csrc/convert_ops.cpp
  torch_xla/csrc/convert_ops.h
  torch_xla/csrc/data_ops.cpp
  torch_xla/csrc/dtype.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/matrix.cpp
  torch_xla/csrc/ops/cast.cpp
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/prod.cpp
  torch_xla/csrc/xla_lower_util.cpp
Labels: runtime

#6240 Experimental GPU PJRT Plugin
  plugins/cuda/README.md
  plugins/cuda/pyproject.toml
  plugins/cuda/torch_xla_cuda_plugin/__init__.py
Labels: runtime

#6271 Fix a typo in aten_xla_type.cpp
  torch_xla/csrc/aten_xla_type.cpp
Labels: TECHNICAL_DEBT

#6178 Adapt a few `torch.utils.checkpoint` functions for PyTorch/XLA.
  torch_xla/utils/checkpoint.py
Labels: xla:gpu

#6235 Remove or simplify hardcoded lists of device types
  .circleci/common.sh
  test/pjrt/test_ddp.py
  test/pjrt/test_runtime.py
  test/pjrt/test_runtime_gpu.py
  test/spmd/test_spmd_debugging.py
  test/spmd/test_xla_distributed_checkpoint.py
  test/spmd/test_xla_sharding_base.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  test/test_ddp.py
  test/test_fsdp_auto_wrap.py
  test/test_metrics.py
  test/test_mp_all_gather.py
  test/test_mp_distributed_mm.py
  test/test_operations.py
  test/test_torch_distributed_all_gather_xla_backend.py
  test/test_torch_distributed_all_reduce_xla_backend.py
  test/test_torch_distributed_multi_all_reduce_xla_backend.py
  test/test_torch_distributed_reduce_scatter_xla_backend.py
  test/test_train_mp_imagenet_amp.py
  torch_xla/_internal/pjrt.py
  torch_xla/amp/autocast_mode.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
  torch_xla/csrc/random.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_registry.cc
  torch_xla/csrc/tensor_impl.cpp
  torch_xla/csrc/xla_backend_impl.cpp
  torch_xla/runtime.py
Labels: runtime

#6285 Temporarily disable GPU coverage workflow in CI
  .github/workflows/build_and_test.yml
Labels: CI

#6253 Add CPU PJRT plugin for testing
  WORKSPACE
  openxla_patches/cpu_compile_options.diff
  plugins/cpu/BUILD
  plugins/cpu/README.md
  plugins/cpu/pjrt_c_api_cpu_version_script.lds
  plugins/cpu/pyproject.toml
  plugins/cpu/test_cpu_plugin.cc
  plugins/cpu/test_cpu_plugin.h
  plugins/cpu/torch_xla_cpu_plugin/__init__.py
Labels: runtime

#6284 Fix some more core aten opset tests
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
Labels: core aten opset

#6273 Set XLA_USE_SPMD for spmd cpp tests.
  test/cpp/test_xla_sharding.cpp
Labels: xla:gpu, SPMD

#6170 Ignore non-XLA nodes and their direct dependents.
  test/dynamo/test_bridge.py
  torch_xla/core/dynamo_bridge.py
Labels: xla:gpu, dynamo

#6278 Reenable ZeRO1 test for GPU to enable coverage for reduce-scatter/all-gather
  test/run_tests.sh
  test/test_mp_early_exit.py
  test/test_zero1.py
  torch_xla/__init__.py
Labels: backport_2.2

#6300 Correct order of constant vs args
  test/stablehlo/test_exports.py
  torch_xla/stablehlo.py
Labels: backport_2.2

#6304 Correct order of constant vs args
  test/stablehlo/test_exports.py
  torch_xla/stablehlo.py
Labels: backport_2.2

#6308 Handle dynamo counter change after fake tensor cache
  test/dynamo/test_dynamo.py
Labels: REMOVE_TORCH_PIN

#6317 [HOT FIX] Disable GPU CI Coverage in master
  .github/workflows/build_and_test.yml
Labels: CI

#6323 Add doc images for auto-sharding
  docs/assets/gpt2_2b_step_time_vs_batch.png
  docs/assets/gpt2_v4_8_mfu_batch.png
  docs/assets/llama2_2b_bsz128.png
  docs/assets/perf_auto_vs_manual.png
Labels: SPMD, documentation

#6328 Add option to register installed plugins automatically
  setup.py
  torch_xla/__init__.py
  torch_xla/experimental/plugins.py
Labels: runtime

#6307 Update metric check for resnet18 dynamo unit test
  test/dynamo/test_dynamo.py
Labels: REMOVE_TORCH_PIN

#6335 Pin to pytorch#117182 (tags/v2.2.0-rc8)
  .torch_pin
Labels: backport_2.2

#6330 Backport PR#6326 to r2.2
  test/pjrt/test_collective_ops_tpu.py
  torch_xla/csrc/init_python_bindings.cpp
Labels: backport_2.2

#6314 Improve build process for PJRT plugins
  .gitignore
  build_util.py
  plugins/cpu/README.md
  plugins/cpu/build_util.py
  plugins/cpu/pyproject.toml
  plugins/cpu/setup.py
  plugins/cpu/torch_xla_cpu_plugin/__init__.py
  plugins/cuda/README.md
  plugins/cuda/build_util.py
  plugins/cuda/pyproject.toml
  plugins/cuda/setup.py
  plugins/cuda/torch_xla_cuda_plugin/__init__.py
  setup.py
Labels: runtime

#6350 [torchbench] Force `llama_v2_7b_16h` to use SGD.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6361 Fix coverage CI run bug & re-enable the EmbeddingBag test with 1% tol
  .circleci/common.sh
  test/pytorch_test_base.py
Labels: bug, CI

#6352 disable some models for torchbench
  benchmarks/experiment_runner.py
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6375 Use `benchmark_cls` for checking precision.`
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6357 Provide op lowering for Logit
  codegen/xla_native_functions.yaml
  test/cpp/test_aten_xla_tensor_1.cpp
  test/test_core_aten_ops.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/elementwise.cpp
  torch_xla/csrc/elementwise.h
  torch_xla/csrc/ops/ops.cpp
  torch_xla/csrc/ops/ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: op lowering

#6373 Add GPU plugin build to CI
  .circleci/common.sh
  infra/ansible/roles/build_srcs/tasks/main.yaml
  plugins/cpu/README.md
  plugins/cpu/build_util.py
  plugins/cpu/setup.py
  plugins/cuda/README.md
  plugins/cuda/build_util.py
  plugins/cuda/setup.py
Labels: runtime

#6360 Define PJRT plugin interface in C++
  torch_xla/__init__.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/pjrt_registry.cc
  torch_xla/csrc/runtime/pjrt_registry.h
  torch_xla/experimental/plugins.py
Labels: runtime

#6389 Force to fp16 models to fp32 if `XLA_USE_FP16` is already set.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6369 Revert: #6368 to fix nightly CI coverage run.
  .circleci/common.sh
  .github/workflows/_test.yml
  .github/workflows/build_and_test.yml
  test/pytorch_test_base.py
Labels: DO_NOT_MERGE

#6402 [torchbench] Re-land: Force `llama_v2_7b_16h` to use SGD.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6416 Use PyTorch's dynamo benchmark skip-list.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6419 [benchmarks] Fix CUDA device check.
  benchmarks/benchmark_experiment.py
Labels: xla:gpu

#6421 Fix distributed checkpoint errors when PyTorch CUDA is enabled.
  test/spmd/test_xla_distributed_checkpoint.py
  torch_xla/experimental/distributed_checkpoint/manager.py
Labels: xla:gpu
