Repository pytorch/xla, pull requests merged in 2024-09, with the labels that each got.

#7938 Add `tpu-info` as a dependency of `torch_xla[tpu]`
  setup.py
  test/tpu/run_tests.sh
  test/tpu/tpu_info/requirements.txt
  test/tpu/tpu_info/test_cli.py
Labels: tpuci

#7918 `DynamicShapeDetector` with trie implementation.
  test/test_dynamic_shapes_detector.py
  torch_xla/csrc/BUILD
  torch_xla/csrc/dynamic_shape_detector.cpp
  torch_xla/csrc/dynamic_shape_detector.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir.cpp
  torch_xla/csrc/ir.h
  torch_xla/torch_xla.py
Labels: dynamism

#7912 Allow MpDeviceLoader to shard dictionaries of tensors
  docs/spmd_advanced.md
  test/run_tests.sh
  test/spmd/test_mp_input_sharding.py
  torch_xla/distributed/parallel_loader.py
Labels: tpuci

#7928 Op info test for special.modified_bessel_i1 .. special.polygamma
  experimental/torch_xla2/test/test_ops.py
  experimental/torch_xla2/torch_xla2/ops/jaten.py
Labels: torchxla2

#7978 Add Build Trigger for 2.5-rc1 release
  infra/ansible/config/vars.yaml
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
  setup.py
Labels: 2.5 release

#8003 Follow 2 releases grace period for API deprecation
  torch_xla/core/xla_model.py
Labels: backport_2.5, 2.5 release

#8006 [benchmarks] Disallow `XRT` for XLA:CUDA.
  benchmarks/benchmark_experiment.py
Labels: xla:gpu

#7916 Update Openxla-pin to Sep13, libtpu-pin to Sep13, jax to 0.4.33_nightly
  WORKSPACE
  setup.py
  test/tpu/run_tests.sh
  torch_xla/__init__.py
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_computation_client_test.cc
  torch_xla/csrc/runtime/profiler.cc
  torch_xla/csrc/runtime/xla_util_test.cc
Labels: tpuci

#8055 Update trigger to 2.5.0-rc3 for 2.5 release
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
Labels: 2.5 release

#8077 cherry pick collective op all_to_all_single
  test/pjrt/test_collective_ops_tpu.py
  test/test_torch_distributed_xla_backend.py
  torch_xla/__init__.py
  torch_xla/csrc/cross_replica_reduces.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/distributed/xla_backend.py
Labels: backport_2.5, 2.5 release

#8078 Force github workflow catch PyTorch commit from release/2.5 branch for PyTorch/XLA `r2.5` branch
  .github/workflows/build_and_test.yml
Labels: 2.5 release

#8052 [cherry-pick] Update Openxla-pin to Sep13, libtpu-pin to Sep13, jax to 0.4.33 stable version
  WORKSPACE
  setup.py
  test/tpu/run_tests.sh
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_computation_client_test.cc
  torch_xla/csrc/runtime/profiler.cc
  torch_xla/csrc/runtime/xla_util_test.cc
Labels: 2.5 release
