Repository pytorch/xla, pull requests merged in 2024-07, with the labels that each got.

#7334 Update OpenXLA-pin to Jun27
  WORKSPACE
  setup.py
  torch_xla/csrc/convolution_helper.cpp
  torch_xla/csrc/dl_convertor.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/lowering_context.cpp
  torch_xla/csrc/lowering_context.h
  torch_xla/csrc/pooling.cpp
  torch_xla/csrc/runtime/debug_macros.h
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client_test.cc
  torch_xla/csrc/runtime/pjrt_registry.cc
  torch_xla/csrc/runtime/profiler.cc
  torch_xla/csrc/runtime/profiler.h
  torch_xla/csrc/runtime/tf_logging.h
  torch_xla/csrc/runtime/util.h
  torch_xla/csrc/runtime/xla_coordinator.cc
  torch_xla/csrc/runtime/xla_util.cc
  torch_xla/csrc/runtime/xla_util.h
  torch_xla/csrc/runtime/xla_util_test.cc
  torch_xla/csrc/xla_graph_executor.h
  torch_xla/csrc/xla_lower_util.cpp
Labels: 2024Q2-manfei-review

#7592 add spmd gpu doc back
  docs/spmd_advanced.md
  docs/spmd_gpu.md
Labels: documentation

#7595 Add documentation for Triton kernels in PTXLA
  docs/triton.md
  test/test_triton.py
Labels: documentation

#7598 [benchmarks] Fix `moco` initialization device.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#7602 Reland: `mul`: convert inputs to result type.
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: xla:gpu

#7604 Handle the parameter wrapping for SPMD
  test/run_tests.sh
  test/spmd/test_spmd_parameter_wrapping.py
  test/tpu/run_tests.sh
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_graph_executor.cpp
Labels: tpuci, backport_2.4

#7318 Introduce CUDA OpenXLA fallback.
  BUILD
  setup.py
  test/cpp/BUILD
  test/test_ops.py
  torch_xla/__init__.py
  torch_xla/core/xla_env_vars.py
  torch_xla/csrc/BUILD
  torch_xla/csrc/aten_autograd_ops.cpp
  torch_xla/csrc/aten_cpu_fallback.cpp
  torch_xla/csrc/aten_cpu_fallback.h
  torch_xla/csrc/aten_cuda_functions.cpp
  torch_xla/csrc/aten_cuda_functions.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/xla_manual_registration.cpp
Labels: xla:gpu

#7629 Update test_pallas.py for CI
  test/test_pallas.py
Labels: tpuci

#7631 fix eager mode spmd module loading with fsdpv2
  test/eager/test_eager_spmd.py
  test/tpu/run_tests.sh
  torch_xla/csrc/aten_xla_type.cpp
Labels: SPMD, eager

#7584 Fallback `_embedding_bag_backward` and force `sparse=false`.
  codegen/xla_native_functions.yaml
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: xla:gpu

#7627 Update jax to a stable version(0.4.29) for r2.4
  setup.py
Labels: tpuci

#7593 separate PyTorch/XLA docs
  docs/source/debug.rst
  docs/source/gpu.rst
  docs/source/index.rst
  docs/source/multi_process_distributed.rst
  docs/source/runtime.rst
  docs/source/spmd.rst
  docs/source/torch_compile.rst
Labels: documentation

#7605 Add blockwise quantized dot support
  docs/quantized_ops.md
  test/quantized_ops/test_quantized_matmul.py
  torch_xla/experimental/xla_quantized_matmul.py
Labels: Quantization

#7611 backport `Enable eager mode for PyTorch/XLA`
  docs/source/index.rst
  examples/eager/train_decoder_only_eager.py
  test/debug_tool/test_pt_xla_debug.py
  test/test_metrics.py
  test/tpu/run_tests.sh
  torch_xla/csrc/debug_util.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.cc
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/xla_graph_executor.cpp
  torch_xla/csrc/xla_graph_executor.h
  torch_xla/experimental/__init__.py
  torch_xla/experimental/eager.py
Labels: backport_2.4

#7626 Asymmetric quantized matmul support
  docs/quantized_ops.md
  test/quantized_ops/test_quantized_matmul.py
  torch_xla/experimental/xla_quantized_matmul.py
Labels: Quantization

#7632 [Fori_loop] Update `randint` max range to Support `bool` dtype
  torch_xla/experimental/fori_loop.py
Labels: fori_loop

#7671 Replace remaining usages of `jax.lax.Precision`
  test/test_gmm.py
  test/test_pallas.py
Labels: tpuci

#7680 Optimize execution for ops that have multiple output in eager mode
  test/eager/test_eager.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
Labels: eager

#7691 Minor update to the docs
  docs/ddp.md
  docs/fsdp.md
  docs/fsdpv2.md
Labels: documentation

#7700 Add docs for eager mode
  docs/eager.md
  docs/source/eager_mode.rst
Labels: documentation, backport_2.4

#7711 Add `tril`, `tile` ops support
  experimental/torch_xla2/test/test_ops.py
  experimental/torch_xla2/torch_xla2/ops/jaten.py
Labels: torchxla2

#7712 Add op support from `nan_to_num` to `movedim`
  experimental/torch_xla2/test/test_ops.py
Labels: torchxla2

#7710 Update eager.md
  docs/eager.md
Labels: documentation

#7715 Update OpenXLA pin as of 07172024
  WORKSPACE
  setup.py
  torch_xla/csrc/runtime/ifrt_computation_client.cc
Labels: tpuci

#7709 Unify the logics to check eager mode
  test/test_operations.py
  torch_xla/__init__.py
  torch_xla/csrc/tensor.cpp
  torch_xla/csrc/tensor.h
  torch_xla/csrc/tensor_methods.cpp
Labels: eager

#7676 Add support for dynamic shape in dynamo
  test/dynamo/test_dynamo.py
  test/dynamo/test_dynamo_dynamic_shape.py
  test/run_tests.sh
  test/tpu/run_tests.sh
  torch_xla/core/dynamo_bridge.py
Labels: dynamism, tpuci

#7724 Re-implement and refactor the verifier.
  benchmarks/benchmark_experiment.py
  benchmarks/benchmark_model.py
  benchmarks/experiment_runner.py
  benchmarks/torchbench_model.py
  benchmarks/util.py
  benchmarks/verifier.py
Labels: xla:gpu

#7630 Make CUDA OpenXLA fallback the default.
  test/test_ops.py
  torch_xla/core/xla_env_vars.py
  torch_xla/csrc/aten_cpu_fallback.cpp
  torch_xla/csrc/aten_cuda_functions.cpp
  torch_xla/csrc/aten_cuda_functions.h
  torch_xla/csrc/device.cpp
  torch_xla/csrc/device.h
Labels: xla:gpu

#7725 Do not try to trim the graph
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/tensor.cpp
Labels: tpuci

#7726 Optimize dynamo dynamic shape caching
  test/dynamo/test_dynamo_dynamic_shape.py
  torch_xla/core/dynamo_bridge.py
Labels: dynamo, tpuci

#7646 Rename `aten_cpu_fallback` into `aten_fallback`.
  CODEGEN_MIGRATION_GUIDE.md
  OP_LOWERING_GUIDE.md
  benchmarks/experiment_runner.py
  configuration.yaml
  torch_xla/csrc/BUILD
  torch_xla/csrc/aten_autograd_ops.cpp
  torch_xla/csrc/aten_cuda_functions.cpp
  torch_xla/csrc/aten_fallback.cpp
  torch_xla/csrc/aten_fallback.h
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/generated_file_include.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/xla_manual_registration.cpp
Labels: xla:gpu

#7718 Fix the SPMD doc strng
  torch_xla/distributed/spmd/xla_sharding.py
Labels: documentation

#7642 Use torch_xla.experimental.compile for all examples
  examples/eager/train_decoder_only_eager.py
  examples/eager/train_decoder_only_eager_multi_process.py
  examples/eager/train_decoder_only_eager_spmd_data_parallel.py
  examples/eager/train_decoder_only_eager_with_compile.py
  examples/train_decoder_only_base.py
  examples/train_resnet_base.py
  torch_xla/experimental/eager.py
  torch_xla/torch_xla.py
Labels: tpuci

#7735 Fix the crash when symint is part of the output with dynamic torch.compile
  test/dynamo/test_dynamo_dynamic_shape.py
  torch_xla/core/dynamo_bridge.py
Labels: tpuci

#7743 fix TPU test regarding word_size
  docs/source/index.rst
  test/pjrt/test_collective_ops_tpu.py
  test/pjrt/test_runtime_multi_cpu.py
  test/pjrt/test_runtime_multi_gpu.py
  test/pjrt/test_runtime_tpu.py
Labels: usability, tpuci

#7747 [benchmarks] Fix batch size logic.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#7749 [benchmarks] Turn CUDAGraphs on for inductor.
  benchmarks/benchmark_experiment.py
  benchmarks/experiment_runner.py
Labels: xla:gpu

#7745 add test for dynamo + traceable collectives
  test/dynamo/test_traceable_collectives.py
  test/run_tests.sh
  test/tpu/run_tests.sh
Labels: tpuci

#7750 Refactor torch_xla.experimental.compile and move it out of experimental
  docs/source/index.rst
  examples/train_decoder_only_base.py
  examples/train_resnet_base.py
  test/eager/test_eager_with_xla_compile.py
  test/test_devices.py
  torch_xla/experimental/eager.py
  torch_xla/torch_xla.py
Labels: tpuci, eager

#7753 clean up deprecated
  docs/ddp.md
  docs/fsdp.md
  docs/pjrt.md
  test/distributed_util.py
  test/pjrt/test_collective_ops_tpu.py
  test/pjrt/test_mesh_service.py
  test/pjrt/test_runtime.py
  test/pjrt/test_runtime_multi_gpu.py
  test/pjrt/test_train_hf_transformer.py
  test/spmd/test_xla_spmd_python_api_interaction.py
  test/test_mp_all_to_all.py
  test/test_mp_collective_permute.py
  test/test_mp_rendezvous.py
  test/test_mp_sync_batch_norm.py
  test/test_profile_mp_mnist.py
  test/test_train_mp_imagenet.py
  test/test_train_mp_imagenet_amp.py
  test/test_train_mp_imagenet_fsdp.py
  test/test_train_mp_mnist.py
  test/test_train_mp_mnist_amp.py
  test/test_train_mp_mnist_fsdp_with_ckpt.py
  test/test_train_mp_mnist_zero1.py
  test/torch_distributed/test_torch_distributed_all_gather_xla_backend.py
  test/torch_distributed/test_torch_distributed_bucketed_all_reduce_xla_backend.py
  test/torch_distributed/test_torch_distributed_multi_all_reduce_xla_backend.py
  test/torch_distributed/test_torch_distributed_reduce_scatter_xla_backend.py
  torch_xla/core/functions.py
  torch_xla/core/xla_model.py
  torch_xla/distributed/fsdp/utils.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
  torch_xla/distributed/spmd/xla_sharding.py
  torch_xla/experimental/deprecation.py
  torch_xla/runtime.py
  torch_xla/test/test_utils.py
Labels: documentation, fixit, tpuci

#7758 openxla pin update
  WORKSPACE
  openxla_patches/cache_urls.diff
  openxla_patches/f16_abi_clang.diff
  openxla_patches/gpu_race_condition.diff
  setup.py
Labels: openxla, tpuci

#7778 Update eager doc to use torch_xla.compile
  docs/eager.md
Labels: documentation

#7775 reenable dynamo dynamic shape test
  test/dynamo/test_dynamo_dynamic_shape.py
  test/run_tests.sh
  test/tpu/run_tests.sh
  torch_xla/core/dynamo_bridge.py
Labels: tpuci

#7781 Update GPU Development Doc for Hermetic Python setup
  docs/gpu.md
Labels: documentation

#7764 Use launch() for all multiprocessing
  API_GUIDE.md
  README.md
  docs/ddp.md
  docs/first_steps.md
  docs/pjrt.md
  examples/data_parallel/train_resnet_xla_ddp.py
  examples/eager/train_decoder_only_eager_multi_process.py
  examples/fsdp/train_resnet_fsdp_auto_wrap.py
  test/debug_tool/test_mp_pt_xla_debug.py
  test/eager/test_eager_all_reduce_in_place.py
  test/pjrt/test_dynamic_plugin_tpu.py
  test/pjrt/test_runtime_tpu.py
  test/pjrt/test_train_hf_transformer.py
  test/test_fsdp_auto_wrap.py
  test/test_mp_all_gather.py
  test/test_mp_all_to_all.py
  test/test_mp_collective_permute.py
  test/test_mp_distributed_mm.py
  test/test_mp_mesh_reduce.py
  test/test_mp_reduce_scatter.py
  test/test_mp_rendezvous.py
  test/test_mp_replication.py
  test/test_mp_save.py
  test/test_mp_sync_batch_norm.py
  test/test_profile_mp_mnist.py
  test/test_torch_distributed_fsdp_frozen_weight.py
  test/test_train_mp_imagenet.py
  test/test_train_mp_imagenet_amp.py
  test/test_train_mp_imagenet_fsdp.py
  test/test_train_mp_mnist.py
  test/test_train_mp_mnist_amp.py
  test/test_train_mp_mnist_fsdp_with_ckpt.py
  test/test_train_mp_mnist_zero1.py
  test/test_zero1.py
  test/torch_distributed/test_ddp.py
  test/torch_distributed/test_torch_distributed_all_gather_xla_backend.py
  test/torch_distributed/test_torch_distributed_all_reduce_xla_backend.py
  test/torch_distributed/test_torch_distributed_bucketed_all_reduce_xla_backend.py
  test/torch_distributed/test_torch_distributed_fsdp_meta.py
  test/torch_distributed/test_torch_distributed_multi_all_reduce_xla_backend.py
  test/torch_distributed/test_torch_distributed_reduce_scatter_xla_backend.py
  torch_xla/distributed/xla_multiprocessing.py
Labels: tpuci
