Repository pytorch/xla, pull requests merged in 2024-04, with the labels that each got.

#6814 Refactor `nms` into TorchVision variant.
  docs/source/index.rst
  test/test_operations.py
  torch_xla/core/functions.py
  torch_xla/csrc/BUILD
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/nms_op.cpp
  torch_xla/csrc/nms_op.h
  torch_xla/csrc/ops/nms.cpp
  torch_xla/csrc/ops/nms.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
  torch_xla/csrc/xla_lower_util.cpp
  torch_xla/csrc/xla_lower_util.h
  torch_xla/csrc/xla_manual_registration.cpp
Labels: xla:gpu

#6873 Fix div lowering and core aten test script enhancement
  test/test_core_aten_ops.py
  torch_xla/csrc/ops/ops.cpp
Labels: backport_2.3

#6875 Add flash attention as custom op so dynamo can trace it
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: pallas

#6883 Fix vector norm lowering
  torch_xla/csrc/tensor_methods.cpp
Labels: backport_2.3

#6881 [benchmarks] Use Torchbench YAML configuration data.
  benchmarks/torchbench_model.py
Labels: xla:gpu

#6661 Add dynamo `torch.Tensor.new` test.
  test/dynamo/test_dynamo.py
Labels: xla:gpu

#6904 Update XLA pin to 04/08/2024
  WORKSPACE
  setup.py
Labels: openxla

#6914 Add `xla.sync`
  test/test_devices.py
  torch_xla/torch_xla.py
Labels: usability

#6917 Build plugin during nightly build
  infra/ansible/Dockerfile
  infra/ansible/e2e_tests.Dockerfile
  infra/ansible/roles/build_plugin/tasks/main.yaml
  plugins/cuda/setup.py
Labels: runtime

#6659 Add dynamo expand test.
  test/dynamo/test_dynamo.py
Labels: xla:gpu

#6942 [Fori_loop|While_loop] Create fori_loop.md
  docs/fori_loop.md
Labels: backport_2.3

#6944 Update XLA pin, 04/19/2024
  WORKSPACE
  setup.py
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/xla_coordinator.h
Labels: tsl

#6946 Update jinja and sphinx versions to address the vulnearbility
  docs/requirements.txt
Labels: TECHNICAL_DEBT

#6955 Reland Install torchvision in release docker #6795 (#6860)
  infra/ansible/Dockerfile
Labels: backport_2.3

#6984 Run TPU CI when label is on PR
  .github/workflows/build_and_test.yml
Labels: tpuci

#6982 [Revert Revert] Update OpenXLA-pin update to Apr25
  WORKSPACE
  setup.py
  test/pjrt/test_runtime_tpu.py
  torch_xla/csrc/runtime/ifrt_computation_client.cc
  torch_xla/csrc/runtime/ifrt_computation_client.h
Labels: tpuci

#6958 Re-land: dynamo expand test with view-replay.
  test/dynamo/test_dynamo.py
  torch_xla/__init__.py
Labels: xla:gpu

#7004 Complain when TensorFlow is installed
  torch_xla/__init__.py
Labels: usability
