Repository pytorch/xla, pull requests merged in 2024-08, with the labels that each got.

#7787 Improve device auto-detection
  test/cpp/cpp_test_util.cpp
  test/cpp/cpp_test_util.h
  test/pjrt/test_profiler.py
  test/pjrt/test_runtime.py
  test/test_operations.py
  test/test_train_mp_imagenet.py
  test/test_train_mp_mnist.py
  torch_xla/__init__.py
  torch_xla/_internal/pjrt.py
  torch_xla/_internal/utils.py
  torch_xla/distributed/spmd/xla_sharding.py
  torch_xla/distributed/xla_multiprocessing.py
  torch_xla/runtime.py
Labels: usability, tpuci

#7760 Add .rst for quantized op doc
  docs/quantized_ops.md
  docs/source/quantized_ops.rst
Labels: documentation, Quantization

#7757 Update function doc strings
  docs/source/index.rst
  torch_xla/core/xla_model.py
  torch_xla/distributed/parallel_loader.py
  torch_xla/distributed/spmd/xla_sharding.py
  torch_xla/runtime.py
Labels: documentation

#6024 Use reduce-scatter coalescing for FSDP
  torch_xla/distributed/fsdp/utils.py
  torch_xla/distributed/fsdp/xla_fully_sharded_data_parallel.py
  torch_xla/utils/checkpoint.py
Labels: backport_2.2

#7797 Update XLA Pin
  WORKSPACE
  setup.py
Labels: tpuci

#7777 [benchmarks] Fix verifier error handling and OOM.
  benchmarks/experiment_runner.py
  benchmarks/verifier.py
Labels: xla:gpu

#7793 Attach callback to a Tensor's underlying buffer
  test/run_tests.sh
  test/test_callback.py
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cc
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/experimental/callback.py
Labels: runtime

#7740 Support fp8e5m2 dtype
  test/run_tests.sh
  test/test_fp8.py
  test/tpu/run_tests.sh
  torch_xla/csrc/dtype.cpp
  torch_xla/csrc/tensor_util.cpp
Labels: fp8

#7812 Support mark_dynamic
  test/dynamo/test_dynamo_dynamic_shape.py
  torch_xla/core/dynamo_bridge.py
Labels: dynamo, tpuci

#7815 Revert "make StepMarker's wait block for async device execution"
  test/test_operations.py
  torch_xla/csrc/xla_graph_executor.cpp
Labels: tpuci

#7809 [benchmarks] Guard empty metrics on verifier runs.
  benchmarks/result_analyzer.py
Labels: xla:gpu

#7826 Add user guide for generating stablehlo composite op
  docs/stablehlo.md
Labels: documentation

#7816 Use local TPU log dir in CI
  .github/workflows/_tpu_ci.yml
Labels: tpuci

#7840 [Pallas] Support ab for flash_attention
  test/test_pallas.py
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#7842 Add fp8e4m3fn support
  test/test_fp8.py
  torch_xla/csrc/dtype.cpp
  torch_xla/csrc/tensor_util.cpp
Labels: tpuci, fp8

#7866 disable test_traceable_collectives
  test/run_tests.sh
  test/tpu/run_tests.sh
Labels: tpuci

#7863 Add Python binding for xla::DotGeneral
  test/quantized_ops/test_dot_general.py
  test/run_tests.sh
  test/tpu/run_tests.sh
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ops/dot_general.cpp
  torch_xla/csrc/ops/dot_general.h
  torch_xla/csrc/ops/xla_ops.cpp
  torch_xla/csrc/ops/xla_ops.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: tpuci

#7864 As_stride should aplly on input tensor, not the base tensor
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
Labels: tpuci

#7878 Fix `norm` data-type when using AMP.
  test/test_operations.py
  torch_xla/csrc/tensor_methods.cpp
Labels: xla:gpu

#7881 Reenable test_traceable_collectives.py
  test/run_tests.sh
  test/tpu/run_tests.sh
Labels: tpuci

#7867 Support dynamic activation quant for per-channel quantized matmul
  test/quantized_ops/test_quantized_matmul.py
  torch_xla/experimental/xla_quantized_matmul.py
Labels: Quantization

#7894 [Op info test] Implemented the following op: exp2 (#7411)
  experimental/torch_xla2/test/test_ops.py
  experimental/torch_xla2/torch_xla2/ops/jaten.py
Labels: torchxla2

#7874 Op info test for `special.i1 .. special.modified_bessel_i0`
  experimental/torch_xla2/test/test_ops.py
  experimental/torch_xla2/torch_xla2/ops/jaten.py
Labels: torchxla2

#7891 update readme for installation
  README.md
Labels: documentation

#7895 CPU time optimization for GraphInputMatcher
  torch_xla/core/dynamo_bridge.py
Labels: dynamo

#7900 Optimize _split_xla_args_tensor_sym_constant
  torch_xla/core/dynamo_bridge.py
Labels: dynamo, tpuci

#7902 Fix the crash with copy op in dynamo
  test/dynamo/test_dynamo.py
  torch_xla/core/dynamo_bridge.py
  torch_xla/csrc/init_python_bindings.cpp
Labels: dynamo

#7108 [OpenXLA-pin-update trigger] Create _openxla_pin_update_weekly.yml
  .github/workflows/openxla_pin_update_weekly.yml
Labels: tpuci

#7909 Move the dynamo bridge to the _dynamo repo
  test/dynamo/test_bridge.py
  test/dynamo/test_dynamo_aliasing.py
  test/dynamo/test_graph_input_matcher.py
  test/dynamo/test_num_output.py
  torch_xla/_dynamo/__init__.py
  torch_xla/_dynamo/dynamo_bridge.py
  torch_xla/core/dynamo_bridge.py
  torch_xla/stablehlo.py
Labels: dynamo

#7910 Update GPU nightly wheel link
  README.md
Labels: documentation

#7860 Support `dist.all_gather` related collective ops
  test/pjrt/test_collective_ops_tpu.py
  torch_xla/core/xla_model.py
  torch_xla/csrc/cross_replica_reduces.cpp
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/distributed/xla_backend.py
Labels: tpuci

#7915 In dynamo optim_mode avoid unnecessary set_attr
  torch_xla/_dynamo/dynamo_bridge.py
Labels: dynamo

#7917 Update the guide for multi process persistent cache
  API_GUIDE.md
  examples/data_parallel/train_resnet_xla_ddp.py
Labels: tpuci

#7927 [benchmarks] Add IR dump option.
  benchmarks/experiment_runner.py
Labels: xla:gpu

#7930 [benchmarks] Fix processing of PyTorch profiler events.
  benchmarks/experiment_runner.py
Labels: xla:gpu
