Repository pytorch/xla, pull requests merged in 2025-05, with the labels that each got.

#9099 Revert "Add `clang` link to `PATH`."
  infra/ansible/config/apt.yaml
  infra/ansible/playbook.yaml
  infra/ansible/roles/install_deps/tasks/main.yaml
Labels: ci-no-td

#9115 [benchmarks] Fix run single config command error
  benchmarks/README.md
Labels: documentation

#9212 Revert "Switch bazel default spawn strategy to `sandboxed`"
  .bazelrc
Labels: ci-no-td

#9273 [torchax] Support View in 'jax_view'
  torchax/torchax/interop.py
Labels: torchxla2
