Repository pytorch/xla, pull requests merged in 2025-01, with the labels that each got.

#8524 [scan] use device_parameter_id_tensor_mapping
  test/scan/test_scan.py
  torch_xla/experimental/scan.py
Labels: tpuci

#8521 Fix DDP with gradient_as_bucket_view enabled
  docs/source/perf/ddp.md
  test/distributed_util.py
  test/torch_distributed/test_ddp.py
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/init_python_bindings.cpp
Labels: tpuci

#8529 [scan] Handle fn output aliasing an input
  test/scan/test_scan.py
  torch_xla/experimental/scan.py
Labels: tpuci

#8536 pin update
  .bazelrc
  WORKSPACE
  setup.py
  test/cpp/test_aten_xla_tensor_2.cpp
  torch_xla/csrc/BUILD
Labels: tpuci

#8540 fix ab in flash attention
  torch_xla/experimental/custom_kernel.py
Labels: tpuci

#8547 Revert "fix batch_norm amp autocast"
  test/test_autocast.py
  torch_xla/csrc/batch_norm.cpp
Labels: tpuci

#8539 [Computation Hash] Introduce deterministic hash for user computations
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/computation_client.cc
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/xla_util.cc
  torch_xla/csrc/runtime/xla_util.h
  torch_xla/csrc/runtime/xla_util_test.cc
  torch_xla/csrc/xla_graph_executor.cpp
Labels: tpuci

#8491 Lower cummax op
  codegen/xla_native_functions.yaml
  test/cpp/test_aten_xla_tensor_2.cpp
  test/test_ops.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/helpers.cpp
  torch_xla/csrc/helpers.h
  torch_xla/csrc/ops/cummax.cpp
  torch_xla/csrc/ops/cummax.h
  torch_xla/csrc/reduction.cpp
  torch_xla/csrc/reduction.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: op lowering

#8551 Introduce HLO graph bindings
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/ir_dump_util.cpp
  torch_xla/csrc/ir_dump_util.h
Labels: tpuci

#8559 pin update
  WORKSPACE
  setup.py
  test/cpp/test_aten_xla_tensor_2.cpp
  torch_xla/csrc/dl_convertor.cpp
  torch_xla/csrc/runtime/BUILD
  torch_xla/csrc/runtime/pjrt_computation_client.cc
Labels: tpuci

#8563 Cherrypick #8521 into r2.6
  docs/source/perf/ddp.md
  test/distributed_util.py
  test/torch_distributed/test_ddp.py
  torch_xla/csrc/aten_xla_bridge.cpp
  torch_xla/csrc/aten_xla_bridge.h
  torch_xla/csrc/init_python_bindings.cpp
Labels: tpuci

#8573 Prepare to make rc5 wheel
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
Labels: 2.6 release

#8571 Re-introduce "XLA_USE_32BIT_LONG" flag
  test/neuron/run_tests.sh
  test/neuron/test_neuron_data_types.py
  test/run_tests.sh
  test/test_data_type.py
  test/tpu/run_tests.sh
  torch_xla/__init__.py
  torch_xla/csrc/dtype.cpp
Labels: tpuci

#8586 prepare rc7 for r2.6 with libtpu update
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
Labels: 2.6 release

#8596 Bump jaxlib to 0.4.38
  setup.py
Labels: tpuci

#8598 Prepare to create 2.6.0rc8 builds
  infra/tpu-pytorch-releases/artifacts.auto.tfvars
Labels: 2.6 release

#8605 Cherrypick #8555
  test/neuron/run_tests.sh
  test/run_tests.sh
  test/scan/test_scan_debug.py
  test/tpu/run_tests.sh
Labels: tpuci

#8604 Cherrypick #8530
  test/scan/test_scan.py
  torch_xla/experimental/scan.py
Labels: tpuci

#8584 Introducing experimental gradient accumulation API
  test/spmd/test_train_spmd_linear_model.py
  test/utils/train_spmd_linear_model_grad_acc.py
  torch_xla/experimental/gradient_accumulation.py
Labels: tpuci

#8608 Introducing experimental gradient accumulation API
  test/spmd/test_train_spmd_linear_model.py
  test/utils/train_spmd_linear_model_grad_acc.py
  torch_xla/experimental/gradient_accumulation.py
Labels: tpuci
