Repository pytorch/xla, pull requests merged in 2025-06, with the labels that each got.

#9184 Refactor GetNumDevices and create GetNumGlobalDevices
  torch_xla/csrc/init_python_bindings.cpp
  torch_xla/csrc/runtime/computation_client.h
  torch_xla/csrc/runtime/ifrt_computation_client.cpp
  torch_xla/csrc/runtime/ifrt_computation_client.h
  torch_xla/csrc/runtime/pjrt_computation_client.cpp
  torch_xla/csrc/runtime/pjrt_computation_client.h
  torch_xla/csrc/tensor_impl.cpp
Labels: distributed

#9318 Revert Create copy of nightly wheel without version number
  infra/ansible/roles/build_srcs/tasks/main.yaml
Labels: ci-no-td

#9330 Update pins
  .bazelrc
  .bazelversion
  WORKSPACE
  setup.py
Labels: dependencies, build

#9306 Fix race condition in runAtenTest
  test/test_utils.py
Labels: testing

#9379 Revert "Avoid unnecessary copy in TensorSource (#8849)"
  torch_xla/csrc/runtime/tensor_source.h
Labels: ci-no-td

#9401 Revert "[torchax]: JittableModule statedict handling"
  torchax/test/test_statedict.py
  torchax/torchax/interop.py
Labels: ci-no-td
