Repository pytorch/xla, pull requests merged in 2025-04, with the labels that each got.

#8926 [CherryPick] Lower `isneginf()`.
  codegen/xla_native_functions.yaml
  test/test_operations.py
  test/test_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
Labels: 2.7 release

#8925 [CherryPick] Lower `isneginf()`.
  codegen/xla_native_functions.yaml
  test/test_operations.py
  test/test_ops.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
Labels: 2.6 release

#9031 Update README for 2.7 release
  CONTRIBUTING.md
  README.md
Labels: documentation

#9011 fix runner cancel issue
  .github/workflows/_build_plugin.yml
  .github/workflows/_build_torch_with_cuda.yml
  .github/workflows/_build_torch_xla.yml
  .github/workflows/_docs.yml
  .github/workflows/_tpu_ci.yml
  .github/workflows/build_and_test.yml
  .github/workflows/lintercheck.yml
  .github/workflows/openxla_pin_update_weekly.yml
  .github/workflows/torchax.yml
Labels: CI
