Repository pytorch/xla, pull requests merged in 2025-03, with the labels that each got.

#8686 Lower `_conj_copy` and `alias` operation.
  codegen/xla_native_functions.yaml
  test/cpp/test_aten_xla_tensor_2.cpp
  test/test_operations.py
  torch_xla/csrc/aten_xla_type.cpp
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
  torch_xla/csrc/tensor_methods.cpp
  torch_xla/csrc/tensor_methods.h
Labels: lowering

#8834 Add info related to codegen
  OP_LOWERING_GUIDE.md
  docs/source/contribute/codegen_migration.md
Labels: documentation

#8817 Add information about codegen in codegen/xla_native_functions.yaml
  codegen/xla_native_functions.yaml
Labels: documentation

#8865 Add lowering for `bitwise_left_shift`.
  codegen/xla_native_functions.yaml
  docs/source/contribute/codegen_migration.md
  test/test_operations.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
Labels: lowering

#8866 Add lowering for `bitwise_right_shift`.
  codegen/xla_native_functions.yaml
  test/test_operations.py
  torch_xla/csrc/ops/ops_lower_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.cpp
  torch_xla/csrc/ops/ops_xla_shape_fn.h
Labels: lowering, DO_NOT_MERGE

#8907 point build to rc3
  infra/tpu-pytorch-releases/artifacts_builds.tf
Labels: 2.7 release
